
#+TAGS: { @Paper:  @Paper_BellLabs @Paper_ETRI @Paper_Precomp @Paper_CoMO  @Paper_PKU @Paper_HW }
#+TAGS: { @Paper: @Paper_KDDI @Paper_NTT }
#+TAGS: { @Paper: @Paper_nakazawa @Paper_nakagawa @Paper_kohno }
#+TAGS: { @Paper: @Paper_Kitayama @Paper_NICT @Paper_osakau }
#+TAGS: { @Paper: @Paper_PAPR @Paper_CHANG @Paper_fudan @Paper_sjtu @Paper_BangorUni }
#+TAGS: { @Paper: @Paper_ZTE }
# #+TAGS: { @PON: @PON_TDM @PON_TWDM }

* Paper, other

** Paper,-SCFDMA [2014-12-18 Thu]

*** COMMENT PAPR, [KEY]: para into serial, so named SC, time-serial
  （2）降低峰平比
  由于OFDM在频域传输的特性，造成OFDM发射机的PAPR（峰平比）较高，需要
大线性范围的功放，且耗电较高。从而对移动终端在上行的应用造成了很多限制。
为了解决这个问题，除了可以在OFDMA基础上采用削波、预留子载波等方法外，
也可以采用线性预处理的方法。LTE上行目前采用的DFT-S-OFDM就是在OFDM的
IFFT（反快速傅立叶变换）操作前增加了一个DFT（离散傅立叶变换），将OFDM
的频域信号恢复到时域，从而降低PAPR。

SC-FDMA的PAPR比起OFDM的PAPR低約1-3dB左右(OFDM的PAPR值較高的原因是由於
多載波在頻域疊加引起). SC-FDMA有較低的PAPR,但在效能上卻不如OFDMA,且
SC-FDMA的複雜度也較OFDMA高

*** \cite{lee2012cpri,-\cite{lee2012cpri}
    - the eye diagram measured at CPRI line rate option 3 is shown. The eyes open clearly, and the extinction
      ratio of 8.8 dB was obtained.
    - extinction ratio and Q factor
    - CPRI line bit rate option 2: 1228.8 Mbit/s. – CPRI line bit rate option 3: 2457.6 Mbit/s. CPRI line bit rate option 4: 3072 0 Mbit/s.
    - The CPRI Specification version 6.1 (in addition to 1.4, 2.1, 3.0 , 4.0, 4.1, 4.2, 5.0, 6.0 )

*** \cite{wu2011optimum},-SLM, ecdf, hist, CCDF
    the probability that PAPR exceeds a threshold PAPR0, can be estimated by
      

** Paper,-Nyquist-SCFDE
*** \cite{ding2013multi},-Nyquist-SCFDE, 
    Nyquist-SCFDE and DFT-Spread-OFDM Superchannel

*** \cite{dong20126}, -Nyquist-band pre-equalization
    # <2014-12-23>

*** \cite{zhang2013nyquist}
    Fig. 1 The diagram of Nyquist-SCFDE systems, Nyquist signal has lower PAPR, which
make it an attractive candidate for optical long-haul
transmission system

*** \cite{kuschnerov2009dsp}, KEY, *cited by 159*


** Paper, SLM
   \cite{bauml1996reducing}, <2014-12-25 Thu>
   
   
** Paper,-MC-CDMA

*** \cite{kumarelectrical}
   1) Electrical Spreading Code-Based OFDM Optical Access Networks
*** \cite{ghanim2012multi},-Multi-user MC-CDMA  
**** \cite{frank2007ifdma},-FDOSS-CDMA
   IFDMA - A scheme combining the advantages of OFDMA and CDMA
   Frequency domain orthogonal signature sequence
   of Frequency Domain Orthogonal Signature
Sequences (FDOSS) has been proposed which maintains the
orthogonality of different users’ signals even for transmission
over multipath channels
 The FDOSS consist of complex ex-
ponentials similar to the complex rotation factors of the DFT
Fig. 1: IFDMA signal generation based on FDOSS CDMA
**** \cite{rindhe2011ofdm},-matlab block
OFDM and MC-CDMA for 4G Networks, matlab block    
***** New and Efficient DWT SC-FDMA System for Image Transmission
       The proposed system uses Discrete Wavelet Transform (DWT) which is
       widely used to transform an image from the spatial domain to
       frequency domain to overcome the high implementation complexity
       drawback of SC- FDMA due to the Discrete Fourier Transform (DFT)
       and Inverse Discrete Fourier Transform (IDFT) operations. S

**** kedia2014performance,-SC-FDMA-DSCDMA
   Performance Analysis of a Modified SC-FDMA-DSCDMA Technique for 4G
   Wireless Communicatio

   Figure 1: Modified SC-FDMA-DSCDMA system model. CDMA spreading operation has been performed before interleaving and
   modulation.
   
As in OFDMA, the transmitters in an SC-FDMA system use different
orthogonal frequencies (subcarriers) to transmit information
symbols. However, these transmitters transmit the subcarriers
sequentially, rather than in parallel. Unlike in OFDMA, this
arrangement reduces considerably the envelope fluctuations in the
transmitted waveform. Therefore, SC-FDMA signals have lower PAPR than
OFDMA signals.


* Paper, TDD, Virtual PON and SDN 				:@Paper_CoMO:

** [CHJ] [KEY]: NO filter, \cite{Xu201220Gbps}, FP-LD as RX, external injection or FBG mode lock
[[papers:Xu201220Gbps][Xu201220Gbps-paper]]

** [SX] \cite{Beppu20142048QAM}, 3.6GHz, 45dB

*** \cite{huang201150}, PDM-I024QAM-OFDM, polarization division multiplexing (PDM) 
We adopted a Nyquist filter with a roll-off factor of 0.2 at the AWG
that enabled us to reduce the bandwidth of the QAM signal to 3.6 GHz.

*** \cite{qian2012high}, PDM-128QAM-OFDM 

** [YCH], [HW] \cite{chand2014demonstration}, 3.1G

** [CQJ] @fpga [FPGA], \cite{Giddings2014Real}, Giddings2014Real,
[[papers:Giddings2014Real][Giddings2014Real-paper]] 

 1) Fig. 6. FPGA to ADC digital interface example.
    1) ADC is 8bit, ADC is 10GSps, so FPGA is 10GSps/8= 2.5GHz

** [#B] [KEY]:  [FPGA] [HW] SD,\cite{Zhou2014Demo}, [[papers:Zhou2014Demo][Zhou2014Demo-paper]]. :@Paper_HW:
[2015-01-28 Wed]
 1) FPGA+ADC
 2) RF-ATT for SD, different SNR for different rate
 3) DML drive power
 4) different SNR, adaptive rate

** [FPGA] EPD, \cite{Watts2007FPGA}, [[papers:Watts2007FPGA][Watts2007FPGA-paper]],
 1) electronic predistortion (EPD)
 2) The drive voltages d1 and d2 that are required to generate the
    predistorted waveform waveform ETX(t) = |ETX(t)| ·exp(i · φ(t))
    were obtained by rearranging (1)
** \cite{Guo2014Cyclic}, TDD, PSS and SSS, carrier frequency offset (CFO), ML
1) PSS
    Primary Synchronization Signal (PSS) and the Secondary
    Synchronization Signal (SSS)
    Symbol and frame timing acquisition, by which the correct symbol
    start position is determined;
2) ML
   maximum likelihood (ML) symbol-time
    
    
** \cite{Hu2013Flexible}, VPN, [[papers:Hu2013Flexible][Hu2013Flexible-paper]]
   [2015-01-05 周一]
   1) Flexible and Concurrent All-Optical VPN in OFDMA PON
   2) virtual private network-(VPN)

   
** [#B] [KEY] \cite{cvijetic2014sdn}, MFH
*** SDN-controlled topology-reconfigurable optical mobile fronthaul architecture for bidirectional CoMP and low latency inter-cell D2D in the 5G mobile era
:PROPERTIES:
:Custom_ID: cvijetic2014sdn
:END:
[[papers:cvijetic2014sdn][cvijetic2014sdn-paper]]
     
** \cite{cvijetic2014next}, [[papers:cvijetic2014next][cvijetic2014next-paper]]
   1) The only constant I am sure of Is this accelerating rate of change.”
** \cite{CPRI_v_6_0_2013-08-30}
*** 4.2. Physical Layer (Layer 1) Specification, pp30
**** Parameter
     - 1, 2, 4*491Mbps
     - 1 chip= 1/3.84MHz
**** 4.2.7.1.1. Framing Nomenclature
The length of a basic frame is 1 TC = 1/fc = 1/3.84 MHz =
260.416667ns. A basic frame consists of 16 words with index
W=0…15. The length T of the word depends on the CPRI line bit rate as
shown in Table 3.
W15B8bit, W15B16bit 
**** Figure 6: CPRI protocol overview
     Motivation for CPRI:
The CPRI specification enables flexible and efficient product
differentiation for radio base stations and independent technology
evolution for Radio Equipment (RE) and Radio Equipment Control (REC).
pp6
Figure 1: System and Interface Definition
*This specification defines the protocols for the physical layer
(layer 1) and the data link layer (layer 2).*

The specification covers layers 1 and 2.
3a. The physical layer (layer 1) supports both an electrical interface
(e.g., what is used in traditional radio base stations), and an
optical interface (e.g. for radio base stations with remote radio
equipment).

3b. Layer 2 supports flexibility and scalability.


**** CPRI line bit rate option 
    - CPRI line bit rate option 1: 614.4 Mbit/s, 8B/10B line coding (1 x 491.52 x 10/8 Mbit/s)
    - CPRI line bit rate option 2: 1228.8 Mbit/s, 8B/10B line coding (2 x 491.52 x 10/8 Mbit/s)
    - CPRI line bit rate option 3: 2457.6 Mbit/s, 8B/10B line coding (4 x 491.52 x 10/8 Mbit/s)

** \cite{Jinno2010Introducing}, OTN, SLICE,  [[papers:Jinno2010Introducing][Jinno2010Introducing-paper]]
1. We hereafter refer to the end-to-end allocated spectral resources
   as an “optical corridor,” which is specified as a set comprising
   the center frequency and width,
2. bandwidth-agnostic

** \cite{Jinno2009Spectrum}, OTN, SLICE, WXC, 
1. spectrum-sliced elastic optical path network (SLICE).
2. wavelength crossconnects-WXCs
3. Wavelength selective switch (WSS)
4. bandwidth agnostic WXCs,


* Paper, Pre-comp, IMD  [2015-01-19 Mon] 		     :@Paper_Precomp:
** [#B] [KEY]: IMD, Lee2009Opto, [[papers:Lee2009Opto][Lee2009Opto-paper]]
*** 3/4a_3A^3, phase is 180, a_3 is related to modulation index, a_3*x(t)^3
*** C part: 2 parts
1) The proposed predistortion method composed of two paths: electrical
   path and distortion path.
*** Lee2009Opto_fig2



** [#C] \cite{Lowery2007Fiber}, pre-comp, for long-haul, [[papers:Lowery2007Fiber][Lowery2007Fiber-paper]]
   [NOTE]: phase modulator 
   1) Fiber nonlinearity pre- and post-compensation for long-haul
      optical links using OFDM
      1) Thus precompensation [6] is advantageous over postcompensation [16].
      2) Electronic Dispersion Compensation (EDC)
   2) [YCH] read
   3) The phase modulator implements the nonlinearity precompensation

** \cite{Lowery2007Fibers}, for long-haul
   1) Fiber Nonlinearity Mitigation in Optical Links That Use OFDM
      for Dispersion Compensation
      1) Precompensation of nonlinearity uses a model of an “inverse”
         fiber at the transmitter, so that the real transmission fiber
         undoes the effects of this “virtual” inverse fiber. The model
         of the inverse fiber typically uses the split-step Fourier
         method [14] to simultaneously solve for the interactions
         between fiber dispersion and nonlinearity.
      2) Because nonlinearity must be computed in the time domain, and
         dispersion is most efficiently computed in the frequency
         domain, a Fourier transform and an inverse-Fourier transform
         are required per section.
      3) To represent fiber nonlinearity, this calculation applies a
         phase advance, \theta(t).
      4) More conveniently, it can be applied in the electrical domain
         using a bank of hardware multipliers just after the inverse
         fast Fourier transform (FFT) at the transmitter.


** \cite{Du2008Improved},  for long-haul
   1) VPItransmissionMaker

** \cite{Du2008Fiber}, for long-haul,  an electrical band limiting filter+phase shifter
    1) Distortion B
       1) In the direct-detection systems, the Q is further degraded
	  because of the nonlinear interaction between the optical carrier
	  and the subcarrier band. This creates an image (Distortion B) of
	  the sideband that falls on the opposite side of the carrier.
    2) be improved by adding an electrical band limiting filter to the
       predistortion signal path.


** \cite{Lin2013pre}, [PKU], Zhangyuan Chen, OFDM, 2013 IEICE 	 :@Paper_PKU:
[[papers:Lin2013pre][Lin2013pre-paper]]
     1) The digital distortion function can be expressed as: d^'(t)=sin^{-1}(Md(t)) /M (3)
     2) Biasing the MZM modulator at quadrature point, the modulator
        has the best linearity for DD-OFDM system.
     3) Mach-Zehnder modulator nonlinearity is pre-compensated

** \cite{Killey2005Electronic}
   1) Fig. 2 Proposed filter architecture
   2) driven by adaptive nonlinear digital filters
** \cite{Killey2005Dispersion}, not yet, optical phase conjugator (OPC) 
   1)  based on a periodically poled lithium-niobate waveguide,

** \cite{chen2013SFDR}, SOP
1) By properly selecting the SOPs launching into the PM and the
   polarizer (i.e. α & θ), and tuning the centre wavelength and
   bandwidth of the optical filter, the combined IMD3 components can
   be cancelled each other at the output polarizer.
2) Pol.: polarizer
3) third-order intermodulation distortions (IMD2 & IMD3)
4) by adjusting the states of polarization (SOPs) launching into the PM and the polarizer
5) Analog photonic links (APLs)
6) polarization modulator (PolM)
7) However, previous schemes may require sophisticated bias control
   circuitry to ease the bias drifting problem
8) However, the main disadvantage of the phase modulated links is the
   complicated receiver architecture.

** \cite{chen2013pre}, 15GHz
1) Pre-Distortion Compensation of Dispersion in APL Based on DSB Modulation
2) By properly tuning the bias of the dual-electrode Mach–Zehnder
   modulator and the relative phase difference between two input RF
   signals
3) 13 and 15 GHz over SMF

** [Shieh] \cite{Shieh2011OFDM}, (Invited Tutorial), real-time, ADC+FPGA
[[papers:Shieh2011OFDM][Shieh2011OFDM-paper]]
   1) OFDM for Flexible High-Speed Optical Networks
   2) (Invited Tutorial)
   3) ADC+FPGA
   4) many landmark works
   5) from a technological point of view, DACs are in fact easier to design than ADCs,
   6) so TX is AWG
   7) Fig. 13. Spectrum assignment in SLICE: (a) conventional optical
      path network, and (b) SLICE [87].


* DONE [#B] paper of SC-FDMA, IFDMA, PAPR 			     :@paper:
  CLOSED: [2015-02-02 Mon 13:41]
  - State "DONE"       from ""           [2015-02-02 Mon 13:41]
  - State "DONE"       from "TODO"       [2015-02-02 Mon 13:40]
  1. [2014-12-08 Mon]

** PAPR, expanding  [2015-09-11 Fri]				:@Paper_PAPR:

*** \cite{yang2015comparison}, hierarchical modulation, @bupt
    1. Comparison of DSP schemes with frequency domain equalization
       for passive optical networks

**** \cite{zhang2013novel}, constellation masking
     1. A novel 3D constellation-masked method for physical security
        in hierarchical OFDMA system

*** [#C] \cite{jiang2010new}, [[papers:jiang2010new][jiang2010new-paper]], Cited by 68, Yuan Jiang
    1. New companding transform for PAPR reduction in OFDM
    2. The author is an independent consultant in Toronto, Ontario,
       Canada (email:yjiang 2001@yahoo.com).

*** \cite{agarwal2015papr}
    1. PAPR reduction using precoding and companding techniques for OFDM systems
    2. In μ-law companding amplitudes of small signals are enlarged
       whereas peaks are unchanged.


** IDMA

*** \cite{ping2007ofdm}, [[papers:ping2007ofdm][ping2007ofdm-paper]], Cited by 103
    1. The OFDM-IDMA approach to wireless communication systems
    2. Interleave-Division Multiple Access (IDMA)

*** \cite{ping2006interleave}, Cited by 580, @wu_keying
    1. Interleave division multiple-access
** IFDMA

*** \cite{onohara2015prototype}, [[papers:onohara2015prototype][onohara2015prototype-paper]], FPGA :@Paper_Kitayama:
    1. 40 nm FPGA
*** \cite{kitayama2013elastic}, [[papers:kitayama2013elastic][kitayama2013elastic-paper]]  :@Paper_Kitayama:
    
*** [#C] \cite{ishii2011low}, [[papers:ishii2011low][ishii2011low-paper]],	OECC2011 :@Paper_Kitayama:
    1. We successfully demonstrated its high power reduction effect of
       93 % compared to FFT/IFFT-based OFDMA-PON systems in the real
       FPGA circuits
    2. Fig. 3. Real DSP circuits for IFDMA-based PON
       1. SRAM-based Processer

*** [#C] [KEY] \cite{yoshida2012experimental}, [[papers:yoshida2012experimental][yoshida2012experimental-paper]], CFO pre-comp, Coherent IFDMA-PON, :@Paper_Kitayama:
  1) Experimental Demonstration of 2xONU 30Gbps
     Digitally-Supported-Coherent IFDMA-PON Uplink
  2) digital carrier frequency offset pre-compensation technique
  3) http://www.mathworks.com/matlabcentral/fileexchange/40291-effect-of-cfo-on-ofdm-system-performance-in-awgn
  4) ML Estimation of Timing and CFO in OFDM systems


*** [INVITED] \cite{ishii2013implementation}, [[papers:ishii2013implementation][ishii2013implementation-paper]], :@Paper_Kitayama:
   1. The power consumption of the real-time IFDMA modulation circuit is 0.82 W

*** \cite{yamamoto2011phase}, [[papers:yamamoto2011phase][yamamoto2011phase-paper]], IFDMA



*** \cite{sorger1998interleaved}, [[papers:sorger1998interleaved][sorger1998interleaved-paper]]
Interleaved FDMA-a new spread-spectrum multiple-access scheme

*** jiang2011experimental,-\cite{jiang2011experimental}, Chen group [2014-12-11 Thu]
TDM-SCFDM-PON
colorless: For the upstream transmission, only one ONU sends signal at
each time slot, so it will not be interfered by other ONUs.


*** [#C] \cite{yang2012cost}, [[papers:yang2012cost][yang2012cost-paper]], PKU,-Zhangyuan Chen

*** time-generation meth-(IFDMA) vs DFT-S-OFDM

**** repetition-->phase rotation-->combination

**** IFDMA为时域方法，DFT-S-OFDM为频域方法
从频域上来看，两种方法得到的子载波映射是相同的。
时域方法IFDMA产生的信号 PAPR较低。
但是相对来说，DFT-S-OFDM更优，所以一般采用DFT-S-OFDM进行局域化或分布式
映射。
这是因为DFT-SOFDM，跟一般的OFDM有一个相似之处，那就是相邻子载波的频谱
是重叠的。普通的IFDMA,载波之间是有保护间隔的。所以IFDMA比DFT-SOFDM频谱
利用率低。

*** [#C] yang2011interleaved, [[papers:yang2011interleaved][yang2011interleaved-paper]], PKU, for paper review
again, [2015-03-06 Fri]
 1) We can see that the IFDMA signal has lowest PAPR compared in
    comparison with OFDMA and DFT-S-OFDM. Moreover, the IFDMA has
    lower computation complexity for the transmitter, which can
    simplify the transmitter and maintain the ONUs cost-effective.
 2) Interleaved Frequency Division Multiple Access for upstream
    Transmission of Next-generation PON

*** [#C] \cite{chien2011comparison}, [[papers:chien2011comparison][chien2011comparison-paper]], -Gee-Kung Chang


** SC-FDMA

*** \cite{zhang2010experimental}, [[papers:zhang2010experimental][zhang2010experimental-paper]], PKU, -Zhangyuan Chen-陈章渊 教授

    - 陈章渊：教授，博导。实验室副主任1997年北京大学电子学系理学博士
      http://ofcl.pku.edu.cn/index.aspx?menuid=6&type=articleinfo&lanmuid=38&infoid=124&language=cn
    - SCFDMA-PON


*** \cite{yang2011performance}, 
 1) Performance Analysis of Uplink IFDMA in the Presence of Carrier
    Frequency Offsets

** [KEY] \cite{farhang2011ofdm}, [[papers:farhang2011ofdm][farhang2011ofdm-paper]]
   1) Cited by 213
   2) Farhang-Boroujeny, B. ; He is an expert in the general area of
      signal processing.
   3) OFDM Versus Filter Bank Multicarrier
** \cite{farhang2010wavelet}
Wavelet-OFDM versus filtered-OFDM in power line communication systems
** \cite{kimura2014energy}
Energy efficient IM-DD OFDM-PON using dynamic SNR management and
adaptive modulation

** Paper Review 5 [2014-12-11 Thu]
# yang2012experimental,-\cite{yang2012experimental}
# Key: propose a smooth evolution scheme from conventional TDM-PONs to
# TDM-OFDM-PON

** [[file:D:/bib1410/paper1410/irfan2013papr.pdf][irfan2013papr]], \cite{irfan2013papr}
** [#A] [[file:D:/bib1410/paper1410/myung2006peak.pdf][myung2006peak]],- \cite{myung2006peak},-\cite{myung2006single}

*** interleaved FDMA-IFDMA

**** (1+SP.subband:Q:numSymbols)

*** localized FDMA-lFDMA

**** ([1:SP.inputBlockSize]+SP.inputBlockSize*SP.subband)

*** distributed FDMA, combined <2014-12-12 周五>



** bhange4single,  SC-FDMA-CDMA, 

   - Single Carrier Frequency Division Multiple Access (SC-FDMA)
     [5-6], is a multiple access techniqueand it utilizes single
     carrier modulation and orthogonal frequencymultiplexing. It has
     been adopted by the third generation partnershipproject (3GPP)
     for uplink transmission in the technology standardized for long
     termevolution (LTE) cellular systems. SC-FDMAis sometimesreferred
     as DFT-spread or DFT-pre-coded OFDMA. 


** OFDM drawback <2014-12-09 Tue>

*** Performance loss in fading channels due to destroyed orthogonality

*** Out-of-band emission problem due to higher PAPR in the frequency domain


* DONE [#C] paper of VLC
  CLOSED: [2015-02-02 Mon 13:41]
  - State "DONE"       from ""           [2015-02-02 Mon 13:41] 
  1. start again, [2015-03-03 Tue]
** @note: @vlc
   1. phosphor of 2MHz| LED of 80MHz | micro-LED of 200MHz | LD of 1.5GHz
      1. [2015-09-25 Fri]
   2. Harald Haas, 爱丁堡大学（University of Edinburgh, @haas
      1. http://www.lifi.eng.ed.ac.uk/
      2. a professor at Jacobs University in Germany
      3. This German Scientist Says Light Bulbs Are The Future Of
         Wireless Data
      4. Harald Haas received his Ph.D. degree from the University of
         Edinburgh, UK, in 2001.
      5. http://purelifi.com/about-us/people/
      6. Harald is an international pioneer of VLC, a world renowned
         expert in wireless communications
      7. The father of Li-Fi, pureLiFi co-founder and Chief Science
         Officer
      8. Prof. Harald Haas is one of only ten the UK’s Recognizing
         Inspirational Science and Engineering (RISE) Award Leaders
         for 2014.
   3. 1000lx upper limit 
   4. @Brien Prof. Dominic O’Brien, Oxford University, UK
   5. Laser Li-Fi Could Blast 100 Gigabits per Second
      1. While LED-based Li-Fi could reach data rates of 10 Gb/s,
         an improvement over the 7 Gb/s maximum of Wi-Fi, using
         lasers could boost that speed to “easily beyond 100 Gb/s,”
         Haas says.
      2. BMW already sells laser-based headlights on its i8
         model. “That is only the start of a technology move as
         laser diodes get more inexpensive,” Haas says.
      3. Lasers, with their high energy and optical efficiency, can be
         modulated at 10 times the rate of LEDs.
      4. The Edinburgh group’s experiment used nine laser diodes.

** [#D] \cite{rajbhandari2015multi}, [[papers:rajbhandari2015multi][rajbhandari2015multi-paper]], @haas, micro-LED of 200MHz
   1. Multi-Gigabit integrated MIMO visible light communication
      system: Progress and updates
   2. In order to increase the available bandwidth Gallium
      Nitride(GaN) micro-LEDs (μLEDs), with a bandwidth of up to
      200MHz were used for a VLC system
   3. Summer Topicals Meeting Series (SUM), 2015
*** [#C] \cite{tsonev2015towards}, [[papers:tsonev2015towards][tsonev2015towards-paper]], 100Gbps
    1. Towards a 100 Gb/s visible light wireless access network
    2. Hence, the visible light spectrum between 390nm and 750nm can
       fit 36 parallel information streams realized at different wavelengths.
    3. 12 RGB triplets (36 individual wavelengths) can fit within the
       visible light spectrum.
    4. then the estimate for the achievable data rate becomes
       105.41Gb/s.
    5. This is approximately 1/12 of the 1000lx upper limit for
       average light illuminance in an indoor environment
    6. With their superior beamforming properties, laser diodes can
       enable extremely high data rate densities, which are
       anticipated in the future Internet of Things.

*** \cite{azhar2013gigabit}, not yet
    1. A Gigabit/s indoor wireless transmission using MIMO-OFDM
       visible-light communications

*** \cite{azhar2013gigabit}, Cited by 117, MIMO, 4*250Mbps
    1. a four-channel multiple-input multiple-output link that uses
       white LED sources, each transmitting signals at 250 Mb/s using
       orthogonal frequency division multiplexing modulation

*** \cite{haas2002space}, [[papers:haas2002space][haas2002space-paper]], @haas
    1. Space-time codes for wireless optical communications
*** \cite{haas2015visible}, [[papers:haas2015visible][haas2015visible-paper]], ppt, @OFC
    1. Visible Light Communication
** [#D] \cite{borogovac2011lights}, lights-off, @bu, L-PPM
   1. “Lights-off” visible light communications
   2. Boston University
   3. how to communicate when the lights are \off."
   4. The LED may achieve 20 MHz of bandwidth, but the phosphor glow
      limits the3dB bandwidth to 2 MHz
   5. In the low transmit power regime one should consider power
      efficient modulations, such aspulse position modulation (L-PPM).
   6. Due to the use of narrow pulses, PPM needs greater bandwidth
      than OOK by a factor L log 2L.
   7. To communicate in the off mode, the lights must emit some light.



** [OFC] [PKU] \cite{zheng2015Experimental}, [[papers:zheng2015Experimental][zheng2015Experimental-paper]], CDMA, :@Paper_PKU:
[2015-04-07 Tue]
 1) CDMA,
 2) Walsh–Hadamard (WH) code
 3) Weiwei Hu
 4) 胡薇薇，女， 博士，北京大学信息科学技术学院教授， 博士生导师
 5) However, compared with a laser, the response of visible light LED
    is too slow to produce high rate optical pulse sequences. Hence
    OOC is not suitable for VLC

** \cite{alaka2015generalized}, Generalized Spatial Modulation
   1. Generalized Spatial Modulation in Indoor Wireless Visible Light
      Communication

** Nakawa Lab in Keio, http://www.naka-lab.jp/index_e.html  :@Paper_nakagawa:
*** @note: 4ppm
    1. Waveform of JEITA Visible Light IDSystem uses Subcarrier
       4-PPM.The Subcarrier 4-PPM has a constantaverage transmission
       power, andit does not cause flickering

*** \cite{kobayashi2000optimal}
   1. Optimal access point placement in simultaneous broadcast system using OFDM for indoor wireless LAN  
*** \cite{kobayashi2002optimal}, [[papers:kobayashi2002optimal][kobayashi2002optimal-paper]],   :@Paper_kohno:
    1. Optimal access point placement in simultaneous broadcast OFDM for public access wireless LAN
*** [#C] \cite{komine2004fundamental}, [[papers:komine2004fundamental][komine2004fundamental-paper]], Cited by 1010, Cited by 963
    1. Fundamental analysis for visible-light communication system
       using LED lights
    2. IEEE Transactions on Consumer Electronics, Vol. 50, No. 1,
       FEBRUARY 2004

** \cite{wang2013demonstration}, [[papers:wang2013demonstration][wang2013demonstration-paper]], @fudan, Chi Nan迟楠 :@Paper_fudan:
   1. 复旦大学信息科学与工程学院教授迟楠
   2. http://it.fudan.edu.cn/People.aspx?id=08216
*** \cite{yuanquan2014high}, uplink of 300Mbps, bandwidth of 80MHz
    1. A high-speed bi-directional visible light communication system
       based on RGB-LED
    2. The overall data rate of downlinkand uplink are 1.15-Gb/s and
       300-Mb/s

*** \cite{chi2015450}, 9Gbps, LD of 1.5GHz
    1. 450-nm GaN laser diode enables high-speed visible light
       communication with 9-Gbps QAM-OFDM
    2. can be extended to1.5 GHz for OFDM encoding after throughput intensity optimization.

*** 复旦大学可见光通讯存缺陷 项目走红负责人始料未及
1) 但其该技术需要有光源，光照不到就没信号，灯光关闭或者被遮挡，网络就
   断了。项目组目前也有研究Dark LED通讯，就是在弱光环境下上网的情况。
2) VLC没有专用芯片组，发射接收系统都非常庞大，这些都是需要完善的，距离
   实用化有相当长的路要走。
*** LiFi存在两大瓶颈
  1) 首先是数据的双向传输问题
  2) 另一个瓶颈就是芯片，这也是最核心的问题
  3) http://network.pconline.com.cn/369/3694217_all.html

*** \cite{wang2014enhanced}, [[papers:wang2014enhanced][wang2014enhanced-paper]], 512QAM
512-ary quadrature amplitude modulation (512-QAM) and wavelength
multiplexing division (WDM), an aggregate data rate of 4.22-Gb/s
based on a combination of frequency domain equalization (FDE) and
decision-directed least mean square (DD-LMS)

*** \cite{wang2014high}, 10Gbps, tdm
  1. while for the uplink, we respectively utilize FDM and time division
   multiplexing (TDM) as the uplink access schemes
  2. For FDM, 4 sub-bands at
   bandwidth of 100MHz are allocated for 4 users.
  3. While for TDM, 4 time slots are assigned for each user to
     transmit upstream signal. The total throughput of uplink and
     downlink for the VLC networks is 4Gb/s.

*** \cite{wang2012training}, [[papers:wang2012training][wang2012training-paper]], TS for VLC [2014-12-08 Mon]
    1. again, [2015-03-03 周二]
    2. Training sequence based frequency-domain channel estimation for indoor diffuse wireless optical communications
    3. 西安电子科技大学（Xidian University）


*  [#C] MFH, *Targeting 48CHNs, 100MHz, 64QAM*  [2014-12-23 Tue]   
  - State "TODO"       from ""           [2014-12-24 Wed 09:17]

** [KEY] OFC2015
   1. http://www.opticsinfobase.org/browseconferences.cfm?meetingid=5&strYr=2015&acronym=OFC

*** \cite{pfeiffer2015next}, [[papers:pfeiffer2015next][pfeiffer2015next-paper]],	   :@Paper_BellLabs:
    1. Pfeiffer, Thomas
    2. radio over Ethernet,  IEEE 1904.3
       1. Furthermore,a  newIEEEprojecthas  recently  been
	  launched(Radio  over  Ethernet,  IEEE  1904.3)to
	  elaborateastandard  for  mapping  and  encapsulatingI/Q
	  samplesinto  standard  Ethernet  frames,  allowing  for
	  reusing  low  costEthernetequipmentfor transmissionand in the
	  long run for also applyingEthernet based networkin
    3. bursty M2M type traffic

*** [OFC] \cite{Neto2015Beyond}, [[papers:Neto2015Beyond][Neto2015Beyond-paper]]
 1) Fabry-Perot Filter
*** [#C] [OFC ] @fpga \cite{Ishii2015Demonstration}, [[papers:Ishii2015Demonstration][Ishii2015Demonstration-paper]], [Kitayama] :@Paper_Kitayama:
[2015-04-07 Tue]
 1) ONU1 (IFDMA/QPSK) ONU2 (OFDMA/16QAM) ONU3 (SC-FDMA/BPSK)
 2) The MUI is one of the major performance limiting factors in the
    OFDMA-PON uplink
 3) ONU1. CFO was pre-compensated in realtime at ONU1.
 4) IFDMA also has a technical issue that its subcarrier assignment is restricted.
 5) The RS(255, 223) is standardized in IEEE 802.3av for 10GE-PON and FEC limit is BER = 1.0×10-3[8,9].

*** [KEY] [OFC] \cite{Cho2015Experimental}, [[papers:Cho2015Experimental][Cho2015Experimental-paper]] 
[2015-04-07 Tue]

*** [SX] Novel Delay-Division-Multiplexing, high-speed DAC to low-speed
[2015-03-26 Thu]
*** [SX] 60*20MHz for MFH

** [#C] [KEY], discuss
*** yamao2013integrated, ppt
    1. it has no ADC/DAC nor up/down converters
       1. Hardware cost will be significantly reduced.
    2. However, multicarrier signal is vulnerable for Nonlinear transmission
    3. http://www.awcc.uec.ac.jp/yamaolab/PDF/RoF_Integrated_NW_Concept_Y.Yamao2.pdf

*** The access line that connects RRU and BBU is so-called “front-haul” 
*** [YCH] FTN due to CP, limited; SC and OFDM for Multi-IFoF; bit loading
[2015-04-14 Tue] 
**** bit loading, 16qam and 64qam
*** Radio-on-Terahertz Over Fiber System
 1) app broker
 2) SMA, sma 接口, SMA (SubMiniature version A) connectors 
*** \cite{liu2015demonstration}, [[papers:liu2015demonstration][liu2015demonstration-paper]], 36 E-UTRA-like wireless signals
    1. Evolved universal terrestrial radio access (E-UTRA) standard
*** [KEY] multi-IFoF, *prior researches, CAPEX*
 1) While wireless signal distribution
    using multi-IFoF technique has experimentally shown in prior researches [5-7],
 2) CPRI, quatilized, 16bit->huge bandwidth consuming, and only OOK
 3) capital expenditures (CAPEX)
 4) intermediate-frequency-over-fiber (IFoF)

*** [KEY] *filtered-OFDM, MSK, IQ compression, all based on filter*, [2015-03-16 Mon]
*** Atsushi Kanno, NICT, [Kitayama], h-index|14|
http://scholar.google.fr/citations?user=HEIoAAgAAAAJ&hl=en&oi=ao

*** |LTE-A |100MHz|64QAM|, |LTE-B|200MHz|256QAM-(no 1024)|
*** TWDM, CWDM, 200G-(1.6nm), 'C' band (1530nm – 1560nm) 
    1) TWDM, uplink, 1560-nm
    2) O-band Original 1260 - 1360
    3) E-band Extended 1360 - 1460.
    4) S-band Short 1460 - 1530

*** [#C] FYI: to [YCH]
  six 100-MHz-bandwidth LTE-A like mobile signals
  HW写错了：HW 是6个chns，每个5-carrier aggregation *20MHz
1) NTT 8CHNs, 200MHz, 256QAM:  title: “256-QAM 8 wireless signal
   transmission with DSP-assisted analog RoF for mobile front-haul in
  LTE-B”
2) HW  6CHNs, 100MHz, 64QAM-(highest in LTE-A), 5-carrier aggregation,
   2*2 MIMO and 3 sectors:
   title: “Efficient Mobile Fronthaul Transmission of Multiple LTE-A
   Signals with 36.86-Gb/s CPRI-Equivalent Data Rate Using a
   Directly-Modulated Laser and Fiber Dispersion Mitigation”
3) ETRI Korea, 20CHNs, 20MHz, 25MHz spacing, 16QAM, \cite{Cho2014cost},


**\cite{ogawa2014recent}, standalization
** [#C] [KEY] MIMO-RoF 					       :@Paper_CHANG:
*** \cite{harjula2008practical}, RoF weights, post IFFT beamforming
    1. Practical issues in the combining of MIMO techniques and RoF in
       OFDM/A systems
    2. delay difference

*** \cite{wang2014investigation}, arcsine pre-distortion technique 
    1. Investigation of Data-Dependent Channel Cross-Modulation in
       Multiband Radio-Over-Fiber Systems

*** \cite{chang2014integrated}, [[papers:chang2014integrated][chang2014integrated-paper]]
    1. Integrated fiber-wireless access architecture for mobile
       backhaul and fronthaul in 5G wireless data networks

*** \cite{zhu2015wavelength}, [[papers:zhu2015wavelength][zhu2015wavelength-paper]]
    1. Wavelength Resource Sharing in Bidirectional Optical Mobile Fronthaul
    2. Fig. 2. Proposed MFH architecture (2). DL: SCM-DWDM-PON; UL:
       UDWDM over DWDM-PON with phase-noise-insensitive heterodyne
       detection.

*** \cite{armada2014radio}, [[papers:armada2014radio][armada2014radio-paper]], BD块对角化(linear), 脏纸编码(nonlinear)
 1) Joint transmission is performed with the aid of Block
    Diagonalization(BD), where the transmitted signal is pre-distorted
    in order to overcomethe non-linearity imposed by the optical
    modulator
 2) then cooperative encoding among the BSs using Dirty Paper Coding
    (DPC) is capable of suppressing the Other Cell Interference (OCI)

*** [#C] [CHANG] \cite{cheng2015high}, [[papers:cheng2015high][cheng2015high-paper]], CoMP-SFBC
  1) High-Diversity Millimeter-Wave CoMP Transmission based on
     Centralized SFBC in Radio-over-Fiber Systems

*** \cite{cheng2014centralized}, pre-coding, MMW difficult to get multiplexing gain 
  1) KEY: A = H^{-1}
  2) Centralized Optical Pre-coding for Multi-cell MIMO in
     Millimeter-wave Radio-over-Fiber System
  3) However, the propagation properties make MIMO at MMW unlikely to
     obtain multiplexing gain since spatial multiplexing usually relies
     on rich multipath propagation. The insufficiency of scattering at
     MMW frequencies result in relatively high spatial correlation,
     which reduces the potential capacity.
  4) Our goal is to use the parameters ai,j and φi,j to compose a
     pre-coding matrixA that is proportional to the inverse of H, as
     written in the figure, assuming the invertibility under a low
     conditionnumber structure. According the correspondence between
     the elements in A and H-1.


*** \cite{cheng2014optical}, [[papers:cheng2014optical][cheng2014optical-paper]]	       :@Paper_CHANG:
  1) Optical CoMP transmission in millimeter-wave small cells for mobile fronthaul

*** [#B] [KEY] [Chang], \cite{cheng2014adaptive}, MFH, photonics-aided CoMP transmissions
[[papers:cheng2014adaptive][cheng2014adaptive-paper]]
cheng2014adaptive_fig3.png
Fig. 7. Experimental setup for the photonics-aided interference cancellation.
**** matrix H
At the front end of the CO, an interference cancellation module is
implemented for realizing the CoMP between the fiber links heading to
two cell sites. Inside the module, attenuation and delay (to cause
linear phase shifting) are implemented according to the feedback from
UEs. 

**** inter-cell interference (ICI)
**** Xiaoli Ma and  Gee-Kung Chang			
1) Lin Cheng (S’09) received the B.S. degree and M.S. degree
   (first-class Hons.) in electronic engineering from Tsinghua
   University,

** 120GHz-band RoF, UTC-PD				      :@Paper_osakau:

*** \cite{fice2012146}, 146-GHz 
    1. 146-GHz millimeter-wave radio-over-fiber photonic wireless transmission system
*** \cite{nagatsuma2013terahertz}, 300 GHz
    1. Terahertz wireless communications based on photonics technologies
*** \cite{nagatsuma2014breakthroughs}, @invited
    1. Breakthroughs in photonics 2013: THz communications based on photonics
*** [#D] \cite{nagatsuma2007multiplexed}, [[papers:nagatsuma2007multiplexed][nagatsuma2007multiplexed-paper]]
    1. Multiplexed transmission of uncompressed HDTV signals using 120-GHz-band millimeter-wave wireless link 
    2. Commercial wireless links using 60-GHz-band MMWs have a data
       rate of over 1.5 Gbit/s and thus acapability of transmitting
       one channel of uncompressed HDSDI signals.
    3. The maximum output power fromthe amplifier-integrated UTC-PD
       now exceeds 10 dBm at 120-GHz band [5].
    4.HD-SDI: high definition serial digital interface) 

*** \cite{hirata2008transmission} 
   1. Transmission characteristics of 120-GHz-band wireless link using radio-on-fiber technologies 
** 220GHz-band RoF
*** \cite{seeds2015terahertz}, @invited
    1. TeraHertz Photonics for Wireless Communications
*** \cite{koenig2012high}, 220GHz, MMIC
    1. High-speed wireless bridge at 220 GHz connecting two
       fiber-optic links each spanning up to 20 km
    2. a mm-wave wireless link(“MilliLink”) maybe used to transmit
       data at high speed anywhere
    3. mm-wave monolithic integrated circuits (MMIC) operating beyond  200GHz
    4. Fiber dispersion limits the 20 Gbit/s OOK signal quality, which
       is not the case for OFDM


** W-band RoF, @RoRoF, @RoFSO, @ITS, 75-110GHz, High-directivity
   1. @date: [2015-08-24 Mon]
*** \cite{chendemonstration}, Ericsson Research
    1. Demonstration of Analog Millimeter-wave Fronthaul Link for
       64-QAM LTE Signal Transmission
    2. realize CPRI over wireless technology but with the drawback of
       poor bandwidth efficiency.
    3. [2015-11-17 Tue]
*** \cite{li2015fiber}, [[papers:li2015fiber][li2015fiber-paper]], @yu_jianjun
    1. Fiber-Wireless-Fiber Link for DFT-spread OFDM Signal
       Transmission at W-Band
    2. fiber-wireless-fiber integration system (FWFI)
    3. act as an emergency “pipe” in physical layers

*** \cite{pleros2008moving}, @ITS
    1. A moving extended cell concept for seamless communication in 60
       GHz radio-over-fiber networks.

*** [#C] \cite{han2015radiate}, [[papers:han2015radiate][han2015radiate-paper]], @ITS
    1. RADIATE exploits the on-roof antenna system to mask the channel
       variation from the users as shown in Fig. 2(b).
    2. Fig. 2. The advantages of RADIATE on addressing the rapid channel variations

    3. RADIATE: radio over fiber as an antenna extender for high-speed
       train communications

    4. we propose a novel solution named RADIATE (RADio-over-fIber as
       AnTenna Extender)

    5. Since the antennas are deployed along the roofof the train, by
       proper antenna selection, the RCS is able tomaintain roughly
       stable wireless communication links betweenthe BS and the train
       for a considerable long time equalingto tens of RTTs.

*** \cite{kitayama2015digital}, [[papers:kitayama2015digital][kitayama2015digital-paper]], W-band MIMO :@Paper_Kitayama:
    1. Digital Coherent W-band MIMO Radio-over-Fiber Systems
    2. high resilience of dual optical wireless link
    3. w/o O/E, multiple DSP to large delay, but using photonic
       mixing and collected DSP 
    4. Fig.2 (a) Individual DSP at RAU and receiver and (b) Collected DSP at receiver
    5. At Tx, the optical two-tone with the frequency interval,equal to the radio frequency carrier fRF (=92.5 GHz) is generated
    6. W-band MIMO RoF transmission link
       1. two-tone Generator

**** \cite{inudo2015mimo}, mimo in W-band RoF 
     1. On the MIMO Channel Rank Deficiency in W-band MIMO RoF transmissions
*** [#D] \cite{pang2014multigigabit}, [[papers:pang2014multigigabit][pang2014multigigabit-paper]], fiber-wireless-fiber
   1. a fiber-wireless-fiber signal relay where a high capacity
      wirelesslink can be used to bridge two access fiber spans over
      physicalobstacles.

   2. Multigigabit W-Band (75--110 GHz) Bidirectional Hybrid
      Fiber-Wireless Systems in Access Networks 

   3. However, it requires the wireless link to possess the
      samecapacity as the fiber-optic link, driving the current search
      foravailable spectrum in the millimeter-wave (mm-wave) and
      thesub-terahertz (sub-THz) region


*** \cite{alavi2014w}, [[papers:alavi2014w][alavi2014w-paper]], frequency nonupling
    1. W-Band OFDM for Radio-over-Fiber Direct-Detection Link Enabled by Frequency Nonupling Optical Up-Conversion

** \cite{tien2015bidirectional}, [[papers:tien2015bidirectional][tien2015bidirectional-paper]], W-band :@Paper_NICT:
   1. Vietnam National University of Agriculture 

   2. Lightwave Devices Laboratory 

      1. http://www2.nict.go.jp/photonic_nw/lwd/en/staff/index.html

   3. Bidirectional Transmission of LTE-A Carrier Aggregati$ion Signal
      over a Seamless Fiber-Wireless System in W-Band

   4. The wireless transmission range can be furtherenlarged using
      high-gain antennas and/or high-output PA, making the system
      suitable for future high-speed and lowlatencymobile front-haul
      networks.

*** \cite{pham2015performance}, not yet
    1. Performance of Uplink Packetized LTE-A Signal Transmission on a
       Cascaded Radio-on-Radio and Radio-over-Fiber System

*** [#D] \cite{kanno2011frequency}, two-tone, Photonics Conference (PHO)
    1. Frequency-stabilized W-band two-tone optical signal generation
       for high-speed RoF and radio transmission

*** [#D] \cite{kanno201290}, [[papers:kanno201290][kanno201290-paper]], photomixer using UTC-PD
   1. 90-GHz radio-on-radio-over-fiber system for linearly located
      distributed antenna systems
   2. Recently, E-band (60-90 GHz) and W-band (75-110 GHz) radio
      technologies havebeen rapidly developed because of their
      availability for radiocommunications.

   3. One difficulty is frequency-stabilized MMW photonicsignal
      generation. Using two free-running lasers to generatethe beat
      note between the wavelength differences
   4. To solve this problem, an opticalmodulation-based MMW signal
      generation technique has beenproposed [13]-[16]. A frequency
      multiplication technique inthe photonic domain can easily
      provide a MMW carrier signalat a frequency higher than 90 GHz.
   5. A radio-on-radio (RoR)concept that the MW radio services is
      encapsulated by theMMW radio was already reported
   6. Thus, the conventional MW radio will be available in the car.


*** \cite{dat2013performance}, [[papers:dat2013performance][dat2013performance-paper]], Globecom
   1. Performance evaluation of lte signal transmission over a
      seamlessly integrated radio-over-fiber and millimeter-wave
      wireless link 

*** \cite{dat2014performance}, @RoRoF, 2 MZMs
    1. Performance of a 90-GHz radio-on-radio-over-fiber system suitable for communications in high-speed railways
    2. The signal is fed into a SMF and up-convertedto a radio-on-radio (RoR) signal at 90-GHz band
    3. The generated two-tone optical signal is then put into a second MZM

*** \cite{dat2010universal}, @RoFSO
    1. A universal platform for ubiquitous wireless communications using radio over FSO system
** [#D] \cite{pham2014heterogeneous}, [[papers:pham2014heterogeneous][pham2014heterogeneous-paper]], @hetnet, @RoRoF 
   1. Heterogeneous wireless signal transmission using seamless
      fiber and millimeter-wave convergence

   2. a seamless fiber-MMW converged system
   3. very high throughput WLAN IEEE 802.11ac signal
   4. Pham Tien Dat
   5. radio-on-radio-over-fiber (RoRoF),

*** \cite{zhu2013demonstration}, bandmapping		       :@Paper_CHANG:
    1. Demonstration of 4-band millimeter-wave radio-over-fiber
       system for multi-service wireless access networks

    2. Fig. 1 illustrates the conceptual diagram of the proposed
       scheme based on band-mapping concept. The wide 60-GHz
       unlicensed band can be divided into four sub-bands,

    3. The 60-GHzband with globally available 7-9-GHz unlicensed
       bandwidth is viewed as a promising candidate for next
       generationvery high throughput (VHT) wireless services.


*** \cite{pham2015high}, [[papers:pham2015high][pham2015high-paper]]
    1. High-speed and low-latency front-haul system for heterogeneous
       wireless networks using seamless fiber-millimeter-wave

*** \cite{beyranvand2015fiwi}, hetnet
    1. FiWi enhanced LTE-A HetNets with unreliable fiber backhaul
       sharing and WiFi offloading

*** \cite{medeiros2015cost}, hetnet
    1. Cost effective Hybrid Dynamic Radio Access supported by Radio over Fiber
** PC-OFDM
*** [#D] \cite{hou2005bandwidth}, HC-MCM, @hou_yafei, Yafei Hou, Cited by 19, PC/HC-MCM
    1. parallel combinatory OFDM (PC-OFDM) systems.
    2. a new method of decreasing the PAPR without reducing the
        bandwidth efficiency and without increasing the bit error
       probability
    3. the OFDM system can be characterized as a systemwith a
       modulation index ∆fT= 1
    4. High compaction multi-carrier modulation (HC-MCM)
    5. http://hamalab.info/?page_id=12
    6. 高知県公立大学法人

** SEFDM
*** \cite{darwazeh2014optical}
    1. Optical SEFDM system; bandwidth saving using non-orthogonal
       sub-carriers

*** \cite{rodrigues2003spectrally}, Cited by 44
    1. A spectrally efficient frequency division multiplexing based
       communication system

*** \cite{mikroulis2015first}, [[papers:mikroulis2015first][mikroulis2015first-paper]], BW compression
    1. First demonstration of a spectrally efficient FDM radio over
       fiber system topology for beyond 4G cellular networking
    2. In this work it is demonstrated that SEFDM technique can be
       successfully supported by radio over fiber systems.

** @RoF, [2015-08-19 Wed]

*** \cite{medeiros2015cost}, hybrid-RoF, WIFI/LTE
    1. Cost effective Hybrid Dynamic Radio Access supported by Radio over Fiber
*** \cite{chanclou2015access}, Xhaul
    1. Access Network for High Speed Applications and Mobile Xhaul
** \cite{anthapadmanabhan2015mobile},			    :@Paper_BellLabs:
   1. Mobile fronthaul over latency-optimized time division
      multiplexed passive optical networks
      
*** \cite{van2011demonstration}, Dora
    1. Demonstration of a symmetrical 10/10 Gbit/s XG-PON2 system
*** \cite{winzer2014making}, @nature
    1. Making spatial multiplexing a reality
    2. https://www.bell-labs.com/usr/peter.winzer

*** \cite{winzer2014spatial}
    1. Spatial Multiplexing in Fiber Optics: The 10X Scaling of Metro/Core Capacities
*** \cite{maes2015past}
    1. The Past, Present, and Future of Copper Access
    2. He is head of the Copper Access research team within the Fixed
       Networks program

*** \cite{foschini1996layered}, Cited by 6934
    1. Cited by 6934
    2. Layered space-time architecture for wireless communication in
       a fading environment when using multi-element antennas

*** [#C] \cite{guo2013lte}, compression, R&D in @ASB
    1. LTE/LTE-A Signal Compression on the CPRI Interface
    2. Figure 4. Frequency spectrum of the original signal and the
       signal pass redundancy removal" block.
    3. BIN GUO is a senior systems engineer in the WirelessResearch
       and Development (R&D)Department at Alcatel-Lucent ShanghaiBell.

*** \cite{marzetta2015massive}
    1. Massive MIMO: An Introduction
*** \cite{viswanathan2014past}
    1. The Past, Present, and Future of Mobile Communications
*** \cite{hoydis2013making}
    1. Making smart use of excess antennas: Massive MIMO, small
       cells, and TDD

*** Bell Labs Technical Journal 
    1. http://ieeexplore.ieee.org/xpl/RecentIssue.jsp?reload=true&punumber=6731002
*** \cite{monteiro2015mobile}, [[papers:monteiro2015mobile][monteiro2015mobile-paper]], SCM, 6*350MHz
    1. Mobile fronthaul RoF transceivers for C-RAN applications
    2. based on Sub-Carrier Multiplexing (SCM) techniques
    3. six 16-QAM channels, each at 1.25 Gbps (nearly to CPRI line rate option 2)
    4. first subcarrier starting at 400 MHz
*** \cite{peng2015contract}
    1. Contract-based interference coordination in heterogeneous cloud
       radio access networks

*** \cite{gordon2013experimental}, precoding, CAS vs DAS
    1. Experimental investigation of antenna selection and transmit
       beamforming for capacity enhancement in 3$\times$ 3
       MIMO-enabled radio-over-fiber DAS
    2. This is in contrast to traditional co-located antenna systems
       (CAS)where antennas are located on the base station
    3. phase-only  transmit  beamforming  and  antenna  selec-tion
    4. multiple eigenmode transmission
    5. antenna selection

*** \cite{kim2007radio}, TDD-based
   1. Radio-over-fiber system for TDD-based OFDMA wireless communication systems 
*** \cite{chia2003radio}, Radio over MMF
    1. Radio over multimode fibre transmission for wireless LAN using VCSELs 
**** \cite{larrode2006overcoming}
    1. Overcoming modal bandwidth limitation in radio-over-multimode fiber links 
*** @5g, @Paper_cvijetic, \cite{cvijetic2014optical}
   1. Optical network evolution for 5G mobile applications and SDN-based control 
   2. TABLE I.COMPARISON OFCPRIALTERNATIVES
      1. Fronthaul Transport  Options
      2. CPRI (time-domain I/Q) | Modulated Symbols | Bit stream |
         Transport Block

*** \cite{nirmalathas2015photonics}, [[papers:nirmalathas2015photonics][nirmalathas2015photonics-paper]]
   1. Photonics for Gigabit Wireless 
*** \cite{gomes2015fronthaul}, [[papers:gomes2015fronthaul][gomes2015fronthaul-paper]], not yet
   1. Fronthaul evolution: From CPRI to Ethernet 
*** \cite{novak2013emerging}
   1. Emerging Disruptive Wireless Technologies: Prospects and Challenges for Integration with Optical Networks 
*** \cite{von2013passive}, [[papers:von2013passive][von2013passive-paper]]
    1. Passive Optical Networks based on OFDM: Perspectives and Experimental Verifications

*** \cite{chow2015convergent}, [[papers:chow2015convergent][chow2015convergent-paper]]
    1. A Convergent Wireline and Wireless Time-and-Wavelength-Division-Multiplexed Passive Optical Network 

** Digitized IFoF

*** \cite{jang2014digitized}, [[papers:jang2014digitized][jang2014digitized-paper]]
    1. A Digitized IF-Over-Fiber Transmission Based on Low-Pass Delta-Sigma Modulation
** \cite{gomes2014fiber}, [[papers:gomes2014fiber][gomes2014fiber-paper]], @invited @CRAN
   1. Fiber link design considerations for cloud-Radio Access Networks
** [#D] \cite{morant2015optical}, [[papers:morant2015optical][morant2015optical-paper]], MIMO-RoF, @Llorente
   1. Optical Fronthaul of LTE-Advanced MIMO by Spatial Multiplexing in Multicore Fiber

*** \cite{alves2013real}, [[papers:alves2013real][alves2013real-paper]], @uwb, CHINESE OPTICS LETTERS
    1. Real-time ultra-wideband video streaming in long-reach passive
       optical networks with wireless radiation in the 10 and 60 GHz
       Bands

*** \cite{morant2014broadband}
    1. Broadband impairment compensation in hybrid fiber-wireless OFDM long-reach PONs
** \cite{ng2012theoretical}, [[papers:ng2012theoretical][ng2012theoretical-paper]], LTE-RoF
 1)  LTE-RoF over varying transmission span

** [#C] CFO and SFO, channel estimation in RoF
*** \cite{tao2013reduction}, [[papers:tao2013reduction][tao2013reduction-paper]], CFO, SFO, window shaping, :@Paper_Chi:
  1) ICI that  is  induced  by  carrier  fre-quency  offset  (CFO)
     and  sampling  frequency  offset  (SFO)
  2) Reduction of intercarrier interference based on window shaping in
     OFDM RoF systems


*** \cite{chen2012pilot}, [[papers:chen2012pilot][chen2012pilot-paper]]
  1) However, in most of the experiments, SFO is usually neglected or
     highly reduced by either carefully tuning RF-sources or by using
     expensive RF sources.

*** \cite{tao2013novel}, [[papers:tao2013novel][tao2013novel-paper]], channel estimation, :@Paper_Chi:
 1) A novel transform domain processing based channel estimation
    method for OFDM radio-over-fiber systems

** @Paper_KDDI, \cite{tanaka2015next}, [[papers:tanaka2015next][tanaka2015next-paper]], compression :@Paper_KDDI:
   1. nonlinear compression
   2. latency, DBA
*** \cite{nanba2013new}, [[papers:nanba2013new][nanba2013new-paper]], compression
    1. A new IQ data compression scheme for front-haul link in centralized RAN
    2. FLAC(Free Lossless Audio Codec)

** @Paper_NTT: SPP 						 :@Paper_NTT:

*** \cite{shibata2015mobile}, [[papers:shibata2015mobile][shibata2015mobile-paper]]
   1. Mobile front-haul employing Ethernet-based TDM-PON system for small cells 
*** \cite{miyamoto2015uplink}, LLR from turbo decoding, @NTT: @AS 大高明浩主任研究員
@date: [2015-07-22 Wed], NTTアクセスサービスシステム研究所（AS研）
   1. Uplink Joint Reception with LLR Forwarding for Optical Transmission Bandwidth Reduction in Mobile Fronthaul 
   2. so optical transmission bandwidth reduction is essential. Although IQ data compression techniques can reduce the bandwidth
   3. Another candidate changes the functional splitting point between BBU and RRH [7, 8] such as the split within the physical (PHY) layer
   4. Finally, soft decision decoding such as the Turbo decoding used in LTE [14] is performed using the combined LLR values 
   5. UEs with 1 antenna and RRHs with 4 antennas
   6. log likelihood ratio (LLR) 

*** \cite{miyamoto2015split}, [[papers:miyamoto2015split][miyamoto2015split-paper]], split-PHY processing (SPP)


** \cite{tao2012spectrally}, [[papers:tao2012spectrally][tao2012spectrally-paper]], Spectrally efficient localized carrier distribution scheme, :@Paper_Chi:
** [#C] Liu Xiang, 48 20-MHz LTE signals demo for mobile fronthaul, energy-efficient  :@Paper_HW:
*** \cite{li2012energy}
    1. Energy conservation via antenna scheduling in fiber-connected
       femto base stations

*** \cite{ragusa2006invertible}, [[papers:ragusa2006invertible][ragusa2006invertible-paper]], invertible clipping
    1. reach an Input Back-Off (IBO) of 1 dB
    2. it is performed thanks to a "soft clipping function"
*** \cite{effenberger2015power}, [[papers:effenberger2015power][effenberger2015power-paper]], DCO (power consuming) | AC | SC, Quadratic “soft” clipping, power efficient
    1. This kind of “soft clipping” avoids spec tral splatter. 
    2. “soft” clipping scheme and its applicability in FDM systems.
    3. Power-efficient method for IM-DD optical transmission of multiple OFDM signals
    4. As a consequence, the soft-clipping produces intermediate signal gains, but with less overall distortion; in other words, it is a trade-off.
    5. We want to produce a new clipping function that has fewer higher order terms. The simplest one is a quadratic
    6. The intensity of the light can only be real and positive. The
       realconstraint is most commonly handled by creating spectra
       with Hermitian symmetry. Thiscomes at the price of spectral
       efficiency;
*** \cite{josse2011model}, energy efficiency
    1. Model for energy efficiency in radio over fiber distributed
       indoor antenna Wi-Fi network

** FSK-OFDM, MSK-OFDM, 连续相位调制解调（CPM）
[2015-05-05 Tue]
*** \cite{morioka2014implementation}, [[papers:morioka2014implementation][morioka2014implementation-paper]], CPFSK-OFDM
 1) CPM is a general term for continuous phase modulation and it
    includes CPFSK, MSK, GMK and so on according to the CPM parameters
    such as modulation index
 2) USRP N210 as the front end of the software defined radio.
 3) this property can mitigate the effects of phase noise and carrier
    frequency offset (CFO), and thus reduces the Inter-Carrier
    Interference (ICI).


*** \cite{shao2011generation}, OFDM-MSK Signal for RoF, Chi Nan

*** http://fr.mathworks.com/help/comm/ref/comm.cpmmodulator-class.html


*** \cite{shao2011novel}, PON
 1) A novel scheme for seamless integration of ROF system with
    OFDM-CPM WDM passive optical network

** \cite{zhang2014clip}, [[papers:zhang2014clip][zhang2014clip-paper]], CFR and DPD, WLAN-Over-Fiber
 1) crest  factor reduction  (CFR)  and  digital  predistortion  (DPD)
 2) 64QAM-OFDM
** [KEY] [HW] \cite{liu2013multiband}, [[papers:liu2013multiband][liu2013multiband-paper]], MB-DFTS-EDC
 1) overlap-and-add scheme
 2) MB-DFTS-EDC

** \cite{kudo2009coherent}, OFDE
  1) using  overlap  frequency  domain equalization  (OFDE)  for  the
     chromatic  dispersion  (CD)

** \cite{yi2007phase}, Phase estimation
 1) Phase estimation for coherent optical OFDM
** \cite{kanesan2012experimental}, [[papers:kanesan2012experimental][kanesan2012experimental-paper]], OMR
  1) optimum, OMI is 0.38
  2) Since LTE signal is composed of OFDM modulation, it is very
     sensitive to phase noise of any form.
** [#C] [KEY] \cite{chen2014demonstration}, [[papers:chen2014demonstration][chen2014demonstration-paper]], DFT-S and conv. :@Paper_Shieh:
 1) Demonstration of software-defined multiband OFDM with
    low-complexity phase noise compensation
 2) In this proposed method,we exploit soft-defined capability of OFDM
    transponder that electronically generates OFDM signal in multiple
    subbands, and apply flexible hybrid modulation onto each subband.In
    particular, among these subbands,only one of them is modulated as DFT-S
    OFDM that has higher complexity,while the others are
    kept conventional OFDM modulation

*** \cite{chen2011experimental}, [[papers:chen2011experimental][chen2011experimental-paper]],  Zadoff-Chu sequence 

*** \cite{chen2015hybrid}, [[papers:chen2015hybrid][chen2015hybrid-paper]], Zadoff-Chu sequences
  1) This implies that the proposed method contributes to more than
     150-fold improvement.
  2) This serves as an evidence to show that the phase noise is uniform
     for different frequencies
  3) aided by the digital filter bank technique
  4) seq(m+1)=exp(−j⋅π⋅R⋅m⋅(m+1)/N), 


** \cite{tolmachev2011low}, polyphase filter

** \cite{tolmachev2011filter}

** \cite{shalom2014improving}

** [invited] \cite{oyama2015nonlinear}, [[papers:oyama2015nonlinear][oyama2015nonlinear-paper]], Invited Paper

** \cite{colavolpe2011faster}, Faster-than-Nyquist
[2015-04-13 Mon]
 1) The improvement is related to the use of narrow optical
    filtering and frequency packing, in order to giving up the signal
    orthogonality in the time and in the frequency domain, 


** [#B] \cite{zhu2015faster}, Faster-than-Nyquist DFT-S-OFDM,  FTN-DFT-S-OFDM.
 1) well-established ICI mitigation techniques such as duobinary pulse
    shaping
 2) mapping, then Duobinary filter
 3) due to inter-sub-band interference (ISBI).

** \cite{wei2015novel}, Novel Delay-Division-Multiplexing OFDMA

** [#B] \cite{liu2015demonstration}, [[papers:liu2015demonstration][liu2015demonstration-paper]], 36 E-UTRA-like, :@Paper_HW:
   1) The aggregation DSP uses a multiband DFT-spread-OFDM like
      structure [11], which contains 36 DFTs followed by one
      12288-point IDFT.

   2) [11] X. Liu et al., “Multiband DFT-spread-OFDM equalizer with
      overlap-and-add dispersion compensation …,” OFC’13, paper OW3B.2
      (2013).

   3) 12288/(16+32+64+128+192+256) = 17.9

** [KEY] \cite{zhu2015high},[[papers:zhu2015high][ zhu2015high-paper]], 60*20MHz, SCM MFH
 1) DWDM-SCM-PON mobile fronthaul system;
 2) An arbitrary waveform generator (AWG) at 5 GSa/s is used to
    generate 12×100MHz (60×20MHz) LTE-A-like CAsignals.

** [KEY] \cite{niiho2006transmission}, multi-IFoF, prior researches
 1) Transmission performance of multichannel wireless LAN system based
    on radio-over-fiber techniques

** [KEY] [KOHNO] \cite{chowdhury2011radio}
[2015-03-23 Mon]
 1) using 60-GHz mm-wave radio-over- fiber technology
 2) Radio over fiber technology for next-generation e-health in
    converged optical and wireless access network


** [#C] \cite{kanno2014radio}, [[papers:kanno2014radio][kanno2014radio-paper]], Radio-on-Terahertz Over Fiber System, :@Paper_NICT:
*** \cite{kanno2014high}, NICT,				
   1) However, the dynamic range of the analog RoF link is an
      important issue because of the relatively high drive voltage of
      optical modulators and the low sensitivity and conversion
      efficiency of optical receivers
   2) an RF sensitivity of less than -90 dBm

*** \cite{dat2014uplink}, NICT, uplink burst
  1) Uplink burst LTE-A signal transmission on a converged
     millimeter-wave and RoF system
  2) In the conventional radio over fiber (RoF) systems, the
     transmitters always irradiate carrier signals even when no radio
     signal is received. This results in low energy-efficient
     systems.
  3) To reduce the power consumption,

** \cite{kubo2014downlink}, TDD
 1) In the LTE specification, the guard time is provided by a special
    sub frame comprising a downlink pilot time slot (DwPTS),guard
    period (GP), and uplink pilot time slot (UpPTS). 


** \cite{chang2014adaptive}, [[papers:chang2014adaptive][chang2014adaptive-paper]], adaptive photonic beamforming :@Paper_Cvijetic:
 1) Adaptive Photonic Beamforming for Physical Layer Security of
    Mobile Signals in Optical Fronthaul Networks
 2) By changing the weights of the FIR filters, the beamformer is made
    adaptive such that it can respond to mobile users and
    dynamically-changing environments.
 3) The adaptive coefficient assignment algorithm used in this work is
    based on the m-ary random search,
 4) Beamformer performance was thus measured in terms of the signal
    strength ratio (SSR) at different locations.
 5) Maximum SSR = 33dB was achieved over 8km SSMF for intended user
    vs. eavesdropper separations from 0.1-0.5 meters, confirming high
    spatial resolution and accuracy of the proposed adaptive
    beamforming approach.
 6) The adaptive finite impulse response (FIR) filters (i.e. frequency
    filter) and remote radio frequency (RF) antenna array
    (i.e. spatial filter) act jointly to form the photonic beamformer.


** \cite{chanclou2013optical}, [[papers:chanclou2013optical][chanclou2013optical-paper]], Cited by 26
 1) the remaining time for round trip time propagation between RRH and
    BBU is only 700 μs for LTE and 400 μs for LTE-Advanced (including
    Coordinated MultiPoint (CoMP)).
 2) Optical fiber solution for mobile fronthaul to achieve cloud radio access network
 3) Calculation of data rate RD per CPRI link is based on the following expression:


** \cite{luo2015two}, PAPR-SLM, not yet
  1) Two improved SLM methods for PAPR and BER reduction in OFDM--ROF
     systems


** \cite{jiang2013novel}, P-SLM, C-SLM, Side info-(SI)
 1) For the P-SLM scheme, there is a phase offset between the signals
    at different transmit antennas, and the phase offset corresponds
    to the phase rotation sequence.
 2) ML-based blind SLM
 3) for the conventional SLM (C-SLM) scheme, extra bits should be
    reserved for the transmission of the phase rotation sequences as
    side information (SI), resulting in the decrease of the data rate.


** \cite{shao201360}, [[papers:shao201360][shao201360-paper]], PTS, CHI-NAN

*** a) Adjacent. (b) Interleaved. (c) Random

** [#C] [Invited], \cite{kanno2015waveform}, [Kitayama], OFCG :@Paper_Kitayama:
  1) Waveform over Fiber
  2) radio-friendly
  3) optical-radio through photomixer
  4) frequency-variable converter using optical frequency comb generator.
  5) an optical frequency comb generation (OFCG) is promising.
  6) DSP-less
     1) A coherent radio over Fiber (RoF) technology helps realizing
       	seamless connectivity between the optical and radio signals using
       	DSPs located at only the edges of the link.6, 7 Using the direct
       	photonic conversion technique using a photomixer and DSP-assisted
       	demodulation technology provides DSP-less radio access units
       	(RAUs) with direct conversion between RoF and radio signals.8,


** \cite{zhang2015full}, OFCG, not yet
 1) A full-duplex WDM-RoF system based on tunable optical frequency
    comb generator

** \cite{frank2005ifdma}, [[papers:frank2005ifdma][frank2005ifdma-paper]]
   1. IFDMA - A Promising Multiple Access Scheme forFuture Mobile Radio Systems

** [#C] \cite{cheng201310}, duobinary and PAM-4 modulations,
   1) 双二进制（duobinary: 双二进制调制采用的方案是使用低于R/2 Hz的带宽传送R bit/s速率的信
      号。由奈奎斯特抽样准则可知，为了无码间干扰（ISI）地传送R bit/s的
      信号，传输脉冲所需的最小的带宽是R/2 Hz。

** \cite{gao2014multi}
A Multi-Band Carrier Aggregation Scheme for Mobile Satellite
Communications
** \cite{shin2014cwdm}, SK Telecom
between BBUs and RRHs through common public radio interface (CPRI) or
open radio interface (ORI)

** \cite{pizzinat2014things}, [[papers:pizzinat2014things][pizzinat2014things-paper]], RoF-(CPRI)
1) Centralized Radio Access Network (C-RAN) architecture. the
   Fronthaul is defined as the segment between the cell site (RU
   location) and the DU hotel.
2) DWDM offers better spectral efficiency than CWDM with typically
   100GHz (0.8nm) or 200GHz (1.6nm) channel spacing.

** [#C] [KEY] [HW], \cite{liu2014efficient}, [[papers:liu2014efficient][liu2014efficient-paper]], -poster deadline paper :@Paper_HW:

1) DML
2) The sizes of the DFT/IDFT used for each channel and for aggregation
   are 192 and 6400, respectively.
3) where n=1,3,5,7,9,11, as shown in Fig. 4(a). Here, we refer to this
   channel mapping as odd-only channel mapping.
4) 64-QAM subcarrier modulation, which is the highest level modulation
   specified in LTE-A
5) Six 100-MHz LTEA-like signals are generated and aggregated through offline DSP


** [#C] [KEY] \cite{Shibata2014256qam}, [[papers:Shibata2014256qam][Shibata2014256qam-paper]], NTT, :@Paper_NTT:

** \cite{shibata2014dynamic}, compression 			 :@Paper_NTT:
 1) Optical Internet 2014 (COIN)
*** \cite{shibata2015dynamic}, [[papers:shibata2015dynamic][shibata2015dynamic-paper]], IQ compression, by filter
   1) compression technique reduced the required optical bandwidth,


** [KEY] Cho2014, \cite{Cho2014cost}, [[papers:Cho2014cost][Cho2014cost-paper]], ETRI, Korea :@Paper_ETRI:
ETRI (electronics and telecommunications research institute)

*** \cite{sung2015improvements}

*** \cite{sung2015improvement}, manuscript
    1. Improvement of the transmission performance in
       multi-IF-over-fiber mobile fronthaul using tonereservation
       technique
    2. In multi-IFoF system, PAPR reduction also should beperformed
       because the transmission performance could be limited by
       inherent nonlinearitiesin directly-modulated laser (DML)

*** [#C] \cite{lee2014ls}, \citep{lee2014ls}, LS for RoF and Jakes, ETRI
    1. H = H_{RoF} \xdot H_{w}
    2. LS channel estimation performance analysis for RoF channel
       environment in the OFDM system
    3. the wireless channel is 1-path Jakes’ fading with the RoF channel
    4. RoF and 1-path Jakes’ fading(10km/h)
    5. PSD 估计信道的均方误差优于最小二乘估计和最小均方误差估计的均方误差

*** Sim is VPI Transmission Maker 9.1TM.
    16 QAM mapped LTE-A baseband OFDM signals with 20 MHz
    bandwidth. the SFDR was quasi-linearly increased with
    Fig. 3. SFDR at different number of IF carrier and EVM as a function of fiber distance at different number of IF
carrier. the maximum allowable number of IF carrier was 20 ea and the minimum IF carrier spacing was 25 MHz,
satisfying the EVM requirement of 12.5%.

*** \cite{chung2014design}, [[papers:chung2014design][chung2014design-paper]], ETRI, Korea
[2015-03-17 Tue]

*** \cite{cho2014investigaitons}, [[papers:cho2014investigaitons][cho2014investigaitons-paper]], ETRI, Korea
*** [KEY] \cite{han2014experimental}, [[papers:han2014experimental][han2014experimental-paper]], ETRI, Korea :@Paper_ETRI:
   1) Analog RF, Analog IQ, Digital IQ
   2) While wireless signal distribution
    using multi-IFoF technique has experimentally shown in prior
    researches [5-7], a proper multi-IF carrier generation method
    for LTE carriers should be investigated
   3) based on analog IQ modulation and digital IQ modulation
   4) Fig.3c,  Analog IQ modulators or LOs are not required,
      1) but the sampling rate of the DAC should be higher


** Work poster deadline paper
   - State "Work"       from ""           [2014-11-25 周二 16:40]

  - \cite{liu2014efficient}, title: efficient mobile fronthaul transmission of multiple LTE-A

  - By applying RoF onto mobile fronthaul, the requirement for channel
    capacity will be significantly reduced as compared to CPRI
    technique. 


* 5GNOW
** @IOT
*** HoloLens - Xbox E3 2015
*** Vehicular Ad Hoc Networks (VANETs) 802.11p

** 5G需要“频谱路线图”保驾护航 
   1. 2015年6月，国际电信联盟(ITU)正式公布5G命名——IMT-2020，以及5G标准
      的完成时间——2020年，也明确了5G的主要性能指标——未来5G网络将至少有
      20Gbit/s的速度，也将能在1平方公里的范围内为超过100万台物联网设备
      提供100Mbit/s以上的平均数据传输速度。以上前所未有的传输速率，必
      然需要相应频谱资源的支持。

** WPAN

*** \cite{lei2008mmse}, [[papers:lei2008mmse][lei2008mmse-paper]], WPAN, MMSE-FDE
    1. Single-Carrier Block Transmission (SCBT) 
** [#C] Gerhard P. Fettweis – Vodafone Chair Professor
** [#C] 5G_note
 1) \\asb-stone\RI_FA_Group\shared\OFDM
 2) http://www.5gnow.eu/
 3) Sparse Code Multiple Access (SCMA), and Filtered-Orthogonal
    Frequency Division Multiplexing (F-OFDM)
 4) 802.11ac only specifies operation in the 5 GHz band. Operation in
    the 2.4 GHz band is specified by 802.11n.
    1) Mandatory 80 MHz channel bandwidth for stations (vs. 40 MHz
       maximum in 802.11n), 160 MHz available optionally
    2) This specification has expected multi-station WLAN throughput
       of at least 1 gigabit per second and a single link throughput
       of at least 500 megabits per second (500 Mbit/s)

 5) Alcatel-Lucent, Huawei Pitch 5G Radio Technologies
    1) http://www.lightreading.com/mobile/5g/alcatel-lucent-huawei-pitch-5g-radio-technologies-/d/d-id/714139
 6) MC, SC; OF(OFDM), FB(FBMC), to NOMA; UF; GFDM (SC, tail biting to
    shorten CP)
 7) NOMA
    1) nominated PDMA (polarization division multiple access), MUSA
       (multiple unit steerable antenna) and Huawei's SCMA

 8) PS (pulse shaping) to lower PAPR by weight (cyclic shift); reduce PAPR
 9) cognitive radio: separate primary and secondary users by filtering process
    1) NC for CR, non-contiguous

** IMT-2020(5G) summit by ITU

*** \\asb-stone\RI_Common_Shared\IMT2020(5G)峰会资料

**** note
    1. International Mobile Telecommunications-Advanced 
    2. http://www.imt-2020.cn/en
    3. flexible duplex
    4. beyond 6G
    5. [HW]: FOFDM, Polar code and SCMA(sparse code)
    6. D2D
    7. SE: 10, PEAK: 50G, EDGE: 1G
    8. 500km/h, 1ms


*** [HUAWEI]
 1. 深度解读华为5G空口新技术：F-OFDM和SCMA颠覆通信技术
    1. http://tele.ofweek.com/2015-03/ART-8320508-8120-28942991_3.html
    2. 前面我们通过F-OFDM已经实现了在频域和时域的资源灵活复用，并把保
       护带宽降到了最小，为了进一步压榨频谱效率，还有哪些域的资源能复
       用呢？最容易想到的当然是空域和码域啊!
    3. F-OFDM已经实现了火车座位(子载波)根据旅客(业务需求)进行了自适应，
    4. 这就涉及SCMA的第一个关键技术—低密度扩频，把单个子载波的用户数
       据扩频到4个子载波上，然后6个用户共享这4个子载波(参见图6)。之所
       以叫低密度扩频，是因为用户数据只占用了其中2个子载波(图中有颜色
       的格子)，另外2个子载波是空的(图中白色的格子)，这就相当于6个乘
       客坐4个座位，那每个乘客的屁股最多坐两个座位嘛。这也是SCMA中
       Sparse(稀疏)的来由。
    5. 对于5G我们希望座位和空间都能够根据乘客的高矮胖瘦灵活定制，硬座、
       软座、卧铺、包厢，想怎么调整都行，这才是自适应的和谐号列车嘛。
       这一切，通过华为提出的F-OFDM就可以做到。

*** Modulation and Coding Scheme (MCS)
** @LAA, \cite{ratasuk2014lte}, [[papers:ratasuk2014lte][ratasuk2014lte-paper]]
   1. LTE in unlicensed spectrum using licensed-assisted access
   2. LAA can be used as a supplementarydownlink (SDL) data channel
      (i.e. downlink only)
   3. II. UNLICENSEDSPECTRUM(5GHZ)
   4. Globecom 2014 Workshop - Telecommunications Standards - From
      Research to Standards
   5. Co-existence mechanism (frequency and LBT)
      1. o Dynamic frequency selection (in response
	 toradar detection)
      2. o Listen-before-talk including clear channel assessment

** eICIC and FeICIC
  1. eICIC (Rel-10) is meant for HetNets where small cell is
     experiencing interference from macro cell. Below is a good
     example from same site:
  2. FeICIC (Rel-11) is also for small cell, and requires the use of
     advanced interference cancellation receivers

** CE

*** \cite{shieh2008maximum}

*** \cite{tao2013transform}, transform domain processing

*** \cite{edfors1998ofdm}, \citep{edfors1998ofdm}, Cited by 1574

*** \cite{van1995channel}, \citep{van1995channel}, 
** [#C] \cite{ghosh2014millimeter}, [[papers:ghosh2014millimeter][ghosh2014millimeter-paper]], NCP-SC
  1) following advantages of NCP-SC still make NCP-SC the preferred
     choice at mmWave frequencies (these advantages hold over both
     OFDM and DFT-S-OFDM):


** [#D] \cite{andrews2014will}, [[papers:andrews2014will][andrews2014will-paper]], Cited by 113
 1) WHO WILL BE THE HEIR OF OFDM

** \cite{boccardi2014five}, Cited by 214
   1. Five disruptive technology directions for 5G
** [#C] ICIC, SFR (HW)

*** SFR, central region is 1, 
 1) Soft Frequency Reuse (SFR) the cell area is divided into two
    regions; a central region where all of the frequency band is
    available and a cell edge area where only a small fraction of the
    spectrum is available.


*** eICIC, blanking of subframes in the time domain,  Almost Blank Subframes (ABS)
 1) To mitigate interference between a macro cell and several pico
    cells in its coverage area, eICIC coordinates the blanking of
    subframes in the time domain in the macro cell. In other words,
    there is no interference in those subframes from the macro cell so
    data transmissions can be much faster.

** Massive MIMO

*** \cite{park2014massive}
 1) Massive MIMO Operation in Fronthaul-capacity Limited Cloud Radio
    Access Networks

** Reconfigurable antenna (inside), beamforming (outside, phase array)
  1. Reconfigurable antennas differ from smart antennas because the
     reconfiguration mechanism lies inside the antenna rather than in
     an external beamforming network.
  2. beamforming: TX/RX gain

** MIMO, STBC, SFBC, MDM (MMF), SM and STC

*** \cite{gordon2014feasibility}, [[papers:gordon2014feasibility][gordon2014feasibility-paper]]
 1) Feasibility Demonstration of a Mode-Division Multiplexed
    MIMO-Enabled Radio-Over-Fiber Distributed Antenna System

*** \cite{diamantopoulos2015mode}, [[papers:diamantopoulos2015mode][diamantopoulos2015mode-paper]]

*** \cite{cheng2014photonic},				       :@Paper_CHANG:

*** \cite{thomas2015single}, [[papers:thomas2015single][thomas2015single-paper]] 


*** \cite{wang2009low}, SFBC
 1) A low-complexity PAPR reduction scheme for SFBC MIMO-OFDM systems


** Equ, Equalization, CFO

***  cyclic prefix reconstruction
*** \cite{kim2011cyclic}, [[papers:kim2011cyclic][kim2011cyclic-paper]], TEQ w/o CP using M-power algorithm
    1. Cyclic prefix free 10-Gb/s OFDM for a DML-based long-reach
       optical access using joint time and frequency domain
       equalization algorithm

    2. In the case of severe ISI, however, there still is a residual
       distortion after the two preceding equalizations due tothe
       accuracy of the LMS filter and one-tap equalizer, especially
       when the numbers of training and pilot symbols arereduced. The
       second TEQ followed by QAM demapper is based on the M-power
       algorithm [4].

    3. \frac{1}{M} \arg \{ \sum_{k=1}(x(k))^M \}


*** \cite{fantacci2004multiuser}, [[papers:fantacci2004multiuser][fantacci2004multiuser-paper]], CFO in uplink

*** [#C] \cite{feng2015performance}, [[papers:feng2015performance][feng2015performance-paper]], CAZAC (polyphase code)
 1) Waveforms consisting more than two phases are called polyphase
    codes. The phase of sub pulse alternate among multiple values
    rather than 00 and 180 0. The sequence can be written as phi(n)=
    (2*pi*i*(n-1))/(p^2)


**** MATLAB
 1) http://www.codeforge.cn/read/174119/cazac.m__html


*** \cite{aziz2012performance}, [[papers:aziz2012performance][aziz2012performance-paper]], CFO
  1) be denoted as 2F-; where β describes the CFO effect. Ifwe
     consider that channel effect is minimal and can beneglected then
     the phase difference of the CP and theOFDM symbol which is the
     victim of CFO can be foundby 2F;-;  2F.

** relay

*** \cite{jin2014performance}, relayed RoF
 1) Performance analysis of full-duplex relaying employing
    fiber-connected distributed antennas

** SC

*** \cite{raghunath2009sc}, [[papers:raghunath2009sc][raghunath2009sc-paper]], 
 1) SC-FDMA versus OFDMA

** [#C] CI-CE-OFDM, Fast-OFDM, VOFDM, BICM, Spectrally Precoded OFDM

*** \cite{chung2006spectrally}, Spectrally Precoded OFDM

*** \cite{von2011constant}, [[papers:von2011constant][von2011constant-paper]], CE-OFDM in PON

*** \cite{nunes2014experimental}, CE-OFDM in PON
 1) Experimental validation of a constant-envelope OFDM system for
    optical direct-detection
    

*** BICM, bit–interleaved coded modulation (BICM)
 1) bit-interleaved before mapping

*** \cite{li2012performance}, [[papers:li2012performance][li2012performance-paper]], VOFDM
 1) On performance of Vector OFDM with Zero-Forcing receiver

*** \cite{ayanoglu2001vofdm}, [[papers:ayanoglu2001vofdm][ayanoglu2001vofdm-paper]], VOFDM, spatial processing
 1) VOFDM broadband wireless transmission and its advantages over
    single carrier modulation.
 2) Spatial processing. In the VOFDM system, spatial processing is
    known as Interference Cancellation.

*** \cite{gao2010performance}, [[papers:gao2010performance][gao2010performance-paper]], CI-OFDM
*** \cite{Thompson2008Constant}, [[papers:Thompson2008Constant][Thompson2008Constant-paper]], Constant Envelope OFDM

*** \cite{Thompson2008Noncoherent}, [[papers:Thompson2008Noncoherent][Thompson2008Noncoherent-paper]]
** [#C] FOFDM, DHT | DCT | DWT | DFT, Fourier (cos and sin), Flash-OFDM, Scalable-OFDM
*** \cite{svaluto2010novel}, DHT, power efficient
[2015-08-03 Mon]
    1. the signal can be transmitted without the need of a DC bias, resulting in a power-efficient system, not affected by clipping noise.
    2. Novel power efficient optical OFDM based on Hartley transform for intensity-modulated direct-detection systems
*** Flash-OFDM, 
  1) flash-OFDM 利用快速跳频技术把信号扩频，具有频率分集能力

*** \cite{giacoumidis2012experimental}, [[papers:giacoumidis2012experimental][giacoumidis2012experimental-paper]], Fast-OFDM, DBPSK-based and double data rate
  1) Experimental Demonstration of Cost-Effective Intensity-Modulation
     and Direct-Detection Optical Fast-OFDM over 40km SMF Transmission
  2) FOFDM,  different  from  conventional  OFDM,  uses  only  half  of
     the  conventional  OFDM  subcarrier  spacing  and  simple
     single-quadrature  modulation  formats.
  3) in optical FOFDM can be implemented by a discrete cosine
      transform (DCT)
  4) DFT: general signal; DCT: even-symmetric signals; DST: odd-symmetric

*** \cite{ibrahim2010demonstration}, [[papers:ibrahim2010demonstration][ibrahim2010demonstration-paper]]
 1) However,  if  the  phase  differences  between the  sub-carriers
    are  controlled,  the  minimumfrequency  spacing  for
    crosstalk-free  operationcan  be  reduced  to  half  of  the
    symbol  rate  persub-carrier.  


*** DWT, Haar Wavelet, no need of CP
 1) simple intros, [LL LH H H], [1 -1]/2
    1) http://www.360doc.com/content/13/0927/14/10724725_317448978.shtml
 2) 主要的区别是小波在时域和频域都是局部的

** SW-CC-CE-OFDM for Sidelobe suppression (SS), precoding and OBM

*** [#C] \cite{paul2009subcarrier}, [[papers:paul2009subcarrier][paul2009subcarrier-paper]], Subcarrier Selection
 1) *bit loading, power loading and subcarrier selection*
 2) In wireless and wireline applications, it iscommon practice to
    apply different powers and modulationalphabets to different
    subcarriers in dependenceon the channel transfer function, which
    is known as”power loading” or ”bit loading”, respectively. In
    digitalsubscriber line (DSL) circuits subcarriers are omittedif
    they suffer from strong external interference (ormight cause
    interference to others).
 3) Subcarrier selection for IM/DD OFDM systems

*** ZC序列由于其星座点发散在一个单位圆上，可以使PAPR很低

*** 星座图扩展（Active Constellation Extension, ACE）和子载波预留（Tone Reservation，TR）

*** \cite{Cosovic2006Suppression}, Cited by 75, MCS (multiple-choice sequences)
*** [#C] \cite{cosovic2006subcarrier}, [[papers:cosovic2006subcarrier][cosovic2006subcarrier-paper]], Cited by 163, SW-OFDM

**** subcarrier weighting (SW)


*** \cite{brandes2005sidelobe}, [[papers:brandes2005sidelobe][brandes2005sidelobe-paper]], constellation expansion (CE) 星座扩展


*** \cite{xu2009precoding}, [[papers:xu2009precoding][xu2009precoding-paper]], precoding for SS

*** [#C] \cite{brandes2006reduction}, [[papers:brandes2006reduction][brandes2006reduction-paper]], CC, Cited by 184

** [#C] COCRAN named by HXA
*** [#C] \cite{milosavljevic2010transparent}, [[papers:milosavljevic2010transparent][milosavljevic2010transparent-paper]], 
  

** IoT machine-type communication (MTC)

*** Gigabit wireless connectivity


** 5GNOW project, UFMC(NOMA), GFDM, FBMC, Coded OFDM, BFDM, NOMA
*** \cite{wunder20145gnow}

*** \cite{luo2015signal}, ZTE


** UFMC

*** matlab, UFMC_OFDM___TransceiverChain_0.m
 1) http://www.5gnow.eu/?page_id=424
*** [#C] \cite{vakilian2013universal}, [[papers:vakilian2013universal][vakilian2013universal-paper]], UFMC

*** \cite{schaich2014waveform}, [[papers:schaich2014waveform][schaich2014waveform-paper]], 
 1) While FBMC performs a per-subcarrier filtering, filtered OFDM
    applies a filtering operation for the entire frequency band. The
    new UFMC solution shown in Figure 1 is a generalization of
    filtered OFDM and FMT


** CR, PU, SU-OFDM
    
*** \cite{qu2010extended}, [[papers:qu2010extended][qu2010extended-paper]], CP for SS, CR-OFDM
*** \cite{ni2014joint}, [[papers:ni2014joint][ni2014joint-paper]],  NC-OFDM-based CR
  1) In  this  paper,  we  propose  a  novel  signal cancelation  (SC)
     method  for  joint  PAPR  reduction  and  sidelobesuppression in
     NC-OFDM-based CR systems.
  2) noncontiguous orthogonal frequency-division multiplexing (NC-OFDM)-
  3) Moreover, the PU subcarriers, which are located in the PUspectrum
     band, need to be turned off to create spectrumnotches to limit the
     interference to the PUs

*** PPT
 1) NC_OFDMA_Spasojevic_2011
    1) http://www.winlab.rutgers.edu/docs/research/documents/NC_OFDMA_Spasojevic_2011.pdf
 2) carrier deactivated  by carrier mask in SU
** [#C] FBMC, staggered, interlace, Wavelet Packet Transform OFDM (WPT-OFDM)
 1) FBMC (staggered multitone, SMT) vs. DMT vs. OFDM
 2) DMT is implemented by FFT is orthogonal FDM. OFDM implemented by
    FFT is discrete multi-tone.
 3) DMT, because of the slowly varying nature of the channel, allows
    spectral shaping by bit-loading, to take advantage of the measured
    channel characteristics.

*** \cite{datta2011fbmc}, [[papers:datta2011fbmc][datta2011fbmc-paper]], 
 1) As shown in [6], sincewe have fewer
    numbers of subcarriers when compared to OFDM, the PAPR of this system
    is better than that of OFDM by about 1 dB at 1%CCDF. 

*** \cite{yuen2010single}, [[papers:yuen2010single][yuen2010single-paper]], SC-FB
 1) Single carrier frequency division multiple access (SC-FDMA) for
    filter bank multicarrier communication systems
 2) We also explored a direct mimicking the SC-FDMA to an FBMC-based
    network
 3) SC-FDMA EXTENSION TO FBMC

*** \cite{matthe2015conjugate}, [[papers:matthe2015conjugate][matthe2015conjugate-paper]], Conjugate-Root Offset-QAM, 
*** \cite{Lin2014FBMC}, windowed CP-FBMC/COQAM (WCP-COQAM).
 1) FBMC/COQAM: An Enabler for Cognitive Radio
 2) This drawback can cause several consequences in CR applications
    because the high out-of-band radiation may severely pollute the
    neighbors in the adjacent bands.

*** [#C] \cite{jung2015amo}, [[papers:jung2015amo][jung2015amo-paper]], FBMC,	      :@Paper_Yonsei:
 1) adaptively modulated optical FBMC based multiple access (AMO-FBMC-MA)
 2) suppress sidelobes,


*** \cite{jung2015mitigation}, using CP extension and FBMC    :@Paper_Yonsei:
  1) In a CP extended OFDM, MAI couldbe reduced with an optimal CP
     length at the sacrifice of SE.
  2) To maintain orthogonal condition between contact subcarriers, an
     offset QAM(OQAM) was also employed in FBMC generation
  3) In OQAM, each subcarrier is assignedalternatively with real and
     imaginary part of QAM signal to ensure orthogonal condition


*** \cite{jung2014amo}, [[papers:jung2014amo][jung2014amo-paper]], MWP,		      :@Paper_Yonsei:
 1) AMO-FBMC based RoF transmission for efficient wired/wireless
    converged optical networks

*** \cite{jung2015adaptation}, [[papers:jung2015adaptation][jung2015adaptation-paper]], AMO-FBMC, :@Paper_Yonsei:

*** \cite{bellanger2010fbmc}

*** [#C] \cite{farhang2010wavelet}, [[papers:farhang2010wavelet][farhang2010wavelet-paper]], 

*** \cite{farhang2011ofdm}

*** [#C] \cite{randel2011study}, [[papers:randel2011study][randel2011study-paper]], OQAM for OC, 

*** \cite{randel2012generation}, OQAM



** BFDM biorthogonal fre- quency-division multiplexing (BFDM), 双正交频分复, 双 多载波调制

*** \cite{kasparick2014bi}, 
** NOMA, non-orthogonal multiple access (NOMA), 非正交多载波调制, 非 多载波调制

** [#C] GFDM, test_vectors.m

*** \cite{michailow2012generalized}, [[papers:michailow2012generalized][michailow2012generalized-paper]]

*** \cite{michailow2011integration}, [[papers:michailow2011integration][michailow2011integration-paper]], GFDM
*** [#C] \cite{lu2015generalized}, [[papers:lu2015generalized][lu2015generalized-paper]], GFMA for RoF
  1) Generalized Frequency Division Multiplexing for Photonic-Assisted
     Millimeter-Wave Carrier Aggregation
*** [#C] [INVITED] \cite{fettweis2009gfdm}, [[papers:fettweis2009gfdm][fettweis2009gfdm-paper]], 
 1) tail biting technique is used to shorten the cyclic prefix in
    order to enhance the spectral efficiency

*** matlab
 1) http://www.5gnow.eu/?page_id=427
 2) load test_vectors.mat, plot(mag2db(abs(ifft([ofdm gfdm]))))


** VOFDM、COFDM、TDS-OFDM和Flash-OFDM


* MMW, WLAN
  1. [2015-05-04 Mon]
** \cite{ho201250}
   1. 50-Gb/s radio-over-fiber system employing MIMO and OFDM modulation at 60 GHz
**  X-band, Q, E and W band
IEEE Radar bands
| Letter Designation | Frequency range |
| X band             | 8 to 12 GHz     |
| Ku band            | 12 to 18 GHz    |
| K band             | 18 to 26.5 GHz  |
| Ka band            | 26.5 to 40 GHz  |
| Q band             | 33 to 50 GHz    |
| U band             | 40 to 60 GHz    |
| V band             | 50 to 75 GHz    |
| E band             | 60 to 90 GHz    |
| W band             | 75 to 110 GHz   |
| F band             | 90 to 140 GHz   |
| D band             | 110 to 170 GHz  |
| G band             | 140 to 220 GHz  |
** \cite{zhang2014multi}, [[papers:zhang2014multi][zhang2014multi-paper]], MMW
 1) Multi-service radio-over-fiber system with multiple base-station
    groups enabled by scalable generation of multi-frequency MMWs

 2) By using the four-wave mixing (FWM) effect in a
    semiconductor optical amplifier (SOA),

** \cite{llorens2014advanced}, not yet, MMW
 1) Advanced Solutions for High Capacity mm-wave Radio over Fiber Systems

** \cite{zhang2014clip}

 1) Clip-and-Filter-Based Crest Factor Reduction and Digital
    Predistortion for WLAN-over-Fiber Links



* [#B] researcher
** [#C] \cite{rappaport2013millimeter}, @shusun, Cited by 355
   1. Millimeter wave mobile communications for 5G cellular: It will
      work
   2. Shu Sun, NYU WIRELESS, Verified email at nyu.edu, Cited by 677
   3. There is, however, little knowledge about cellular mm-wave propagation 
   4. Obtaining this information is vital for
   5. SHUSUN(ss7152@nyu.edu) received her B.S. degree inapplied physics
      from Shanghai Jiao Tong University, China,in 2012. She is
      currently working toward a Ph.D. degree inelectrical engineering
      at Polytechnic School of Engineering,New York University (NYU),
      Brooklyn, and is doing researchat the NYU WIRELESS research
      center

** [#C] \cite{chen2010closed}, @chenxi, Cited by 101
   1. Closed-form expressions for nonlinear transmission performance
      of densely spaced coherent optical OFDM systems

*** \cite{al2011dual}, Cited by 92, @chenxi, TMF
    1. Dual-LP 11 mode 4x4 MIMO-OFDM transmission over a two-mode fiber
    2. However, these fibers may support 100 or more modes which
       couple witheach other during transmission of even moderate
       distance in a random manner due toenvironmental perturbation,
       therefore practical demonstrations of MDM in MMF is limited
       tousing a limited number of modes and using some form of
       spatial filtering

*** An Li
    1. Research Fellow, Department of Electrical and Electronic
       Engineering, The University of Melbourne
    2. Optical Communications, Fiber Sensors
    3. Verified email at unimelb.edu.au


** Jianjun Yu
   1. Fudan University / ZTE Corp.
   2. Verified email at mail.gatech.edu
   3. Cited by 8623

** @tuyouyou

*** 中科院上海有机化学研究所吴毓林
    1. 吴毓林  (2009)  青蒿素――历史和现实的启示．化学进展  21:2365-2371
    2. 周维善的果子,为什么由屠呦呦摘
    3. 屠呦呦的师兄兼同事。一生为了青蒿素呕心沥血，于2012年病逝

*** 《诗经》里说，“呦呦鹿鸣，食野之苹”

*** 在她并未被业界看好的情况下，曾有一个人力荐过屠呦呦获诺奖, 饶毅
    1. 他就是饶毅。饶毅在科学界知名度很高，但不见得都知道他

** lilinyi
 1. http://front.sjtu.edu.cn/~llyi/
 2. 义理林副教授，博士生导师全国优博论文/NSFC优秀青年基金获得者上海市东
   川路800号交通大学电信群楼5-517室    
** Kitayama
  1. Ministry of Internal Affairs and Communications. 総務省 Sōmu-shō
  2. He received the Ministry of Internal Affairs and Communications
     Award in 2014


** W. Shieh, ACADEMIC PRESS, 2009

** 寺田 純-Terada Jun
 1) http://ci.nii.ac.jp/author?q=%E5%AF%BA%E7%94%B0+%E7%B4%94&sortorder=1&count=20&start=21
 2) NTT Access Network Service System Labs

** 吉本 直人 YOSHIMOTO Naoto
 1) http://ci.nii.ac.jp/nrid/9000004738125/?sortorder=1&count=20&start=21
 2) NTT Access Network Service Systems Laboratories


** 菅野 敦史, かんの あつし, KANNO Atsushi, 主任研究員
 1) http://www2.nict.go.jp/photonic_nw/lwd/staff/index.html


** NICT, 1st Workshop on Convergence of radio and optical technologies 
 1) http://www2.nict.go.jp/photonic_nw/lwd/en/event/20140822/index.html

* Review of PON

** coexistance

*** DC-PON, digital coherent PON, \cite{iiyama2015advanced}, [[papers:iiyama2015advanced][iiyama2015advanced-paper]]

*** \cite{deng2011experimental}
 1) Experimental demonstration of an improved EPON architecture using
    OFDMA for bandwidth scalable LAN emulation

** coherent, OOTDM, FMF and MCF; 3m

*** \cite{matsuo2013recent}, FMF
   1. Recent progress in multi core and few mode fiber 

*** @Paper_nakazawa, 3m, OTDM				   :@Paper_nakazawa:
**** \cite{nakazawa2012extremely}, [[papers:nakazawa2012extremely][nakazawa2012extremely-paper]], 3m
     1. Extremely advanced transmission with 3m technologies (multi-level modulation, multi-core \& multi-mode)
     2. “orthogonal” OTDM (O-OTDM)
     3. Cited by 88
**** \cite{nakazawa2012ultrahigh}, [[papers:nakazawa2012ultrahigh][nakazawa2012ultrahigh-paper]]
     1. Ultrahigh-speed “orthogonal” TDM transmission with an optical Nyquist pulse train
**** \cite{koizumi20121024} Masataka Nakazawa 中沢教授室
     1. 1024 QAM (60 Gbit/s) single-carrier coherent optical transmission over 150 km
     2. http://www.nakazawa.riec.tohoku.ac.jp/Japanese/index_flame.shtml 


** @ECOC, @SIGCOMM

*** \cite{vissicchio2015central}, @SIGCOMM
    1. Central control over distributed routing
    2. Proceedings of the 2015 ACM Conference on Special Interest
       Group on Data Communication

*** @bell-labs
    1. demonstration of 112 Gbit/s optical transmission using 56 Gbaud PAM-4

*** FDW, frequency domain windowing 				  :@Paper_HW:
  1. experimental demonstration of high-throughput low latency mobile fronthaul								  1. 
  2. FDW to reduce latency

*** w/ predistorter						:@Paper_ETRI:
    1. linear improvement of directly-modulated multi-IF-over fiber
** @asb, \cite{xiao2015colorless}
   1. A colorless remote node for metro-access converged optical network
   2. SPIE OPTO
** @keysight,  N4392A Integrated Optical Modulation Analyzer 
   1. [2015-09-06 Sun]
** Copper

*** note
  1. CAT5, Short for Category 5, network cabling that consists of four twisted pairs of copper
  2. NEXT, FEXT, ECHO

*** [#C] \cite{cendrillon2004improved}, [[papers:cendrillon2004improved][cendrillon2004improved-paper]], Diagonalizing Precompensator
    1. CWDD, Columnwise diagonal dominance
*** \cite{karipidis2006crosstalk}
   1. Crosstalk models for short VDSL2 lines from measured 30MHz data 
*** \cite{perez2008optimal}

*** \cite{xu2009stochastic}

*** \cite{coomans2014xg}, [[papers:coomans2014xg][coomans2014xg-paper]], XG-FAST, bonding and phantom :@Paper_Bell-Labs:
    1. The  combination  of  bonding  and  phantom  mode  on  two
       twisted pairs could potentially provide a threefold increase in
       data  rate  when  compared  to  the  data  rate  achievable
       over  a single  twisted  pair.
    2. 500MHz, 10Gbps

*** [#C] \cite{kavehrad200310}, [[papers:kavehrad200310][kavehrad200310-paper]], MIMO-DFE

*** [#C] \cite{ginis2000multi}, [[papers:ginis2000multi][ginis2000multi-paper]], TH-precoder
  1. Cited by 112
** COCO, COCRAN, Cloud-DSL, ECDMA-PON, converged fiber/copper networks

*** 基于扩频编码的无源光网络关键技术研究

*** [#C] \cite{rosas2009high}, [[papers:rosas2009high][rosas2009high-paper]], 18Gcs, ECDMA
  1. However, an almost ten-fold improvement to 18 Gchip/s was
     achieved recently using electronic finite impulse response (FIR) filters
  2. The Chip Rate = User Rate × No. ofUsers (7, 15, 31, 63, … for Gold codes).
  3. The original 1.25 Gb/s data spectrum
  4. TF: transversal filters.


*** [#C] Cloud-DSL, FTTDp, \cite{fang2015demonstration}, [[papers:fang2015demonstration][fang2015demonstration-paper]], eCDMA+DMT :@Paper_HW:
  1) fiber-to-the-drop-point (FTTDp)
  2) eCDMA for SImple CA
  3) fiber drop points (FDPs)
  4) customer-premises equipments (CPEs)

** [#C] \cite{yang2014optimum}, [[papers:yang2014optimum][yang2014optimum-paper]], RF-Clipping
  1. To broaden the optical spectrum, we directly modulated the
     RF-clipping tone (optical modulation index >1)
  2. it is preferable to locate the clipping tone far away from the
     DMT signal band over a 3-dB range of the LD’sfrequency response
  3. trade-off between the optical spectrum broadening effect and the dither effect


** TWDM-PON

*** \cite{luo2014next},						  :@Paper_HW:
    1. Next generation hybrid wireless-optical access with TWDM-PON
** DMT-PON

*** \cite{milion2009high}, [[papers:milion2009high][milion2009high-paper]]
  1. The  main  difference  between  DMT  and  OFDM  is
     thepossibility to adapt the modulation order as well as thepower
     level    per    sub-carrier    according    to
     thecorresponding channel state information (CSI


** COF-PON, FO-CDMA-PON
code-division-multiplexing (CDM) over-fiber passive optical network (COFPON)

*** \cite{mehedy2010frequency}, spectrally efficient for PON
  1) Frequency interleaving towards spectrally efficient directly
     detected optical OFDM for next-generation optical access networks


** \cite{van2012demonstration}, Bi-PON, @fpga
   1. Demonstration of low-power bit-interleaving TDM PON
** \cite{liu2015simplified}, [[papers:liu2015simplified][liu2015simplified-paper]], PPM-PON
** CAP, carrier-less amplitude/phase modulation (CAP)

** \cite{zhao2011offset}, OQAM
** [#C] \cite{Chand2014Demonstration}, [[papers:chand2014demonstration][chand2014demonstration-paper]], coexistence, :@Paper_HW:
 1) Demonstration of Coexistence of Legacy Video and OFDM-PON in the Video Wavelength Band
** \cite{zhou2015demonstration}
 1) Demonstration of a novel software-defined Flex PON
** \cite{Cheng2013Flexible}, 
  1) Flexible TWDM PON with load balancing and power saving
  2) Amplitude & Phase : 3 bits
** [#C] \cite{iiyama2013two}, [[papers:iiyama2013two][iiyama2013two-paper]], star-8QAM, ASK+PSK
[2015-04-24 Fri]
  1) the OLT generates a star 8-QAM signal by modulating 1 bit, b1,
     with ASK and 2 bits, b2 and b3, with PSK as shown in Fig. 2 (a).
  2) coexistance

** XiaofengPTL, \cite{hu2011reconfigurable}, All-Optical VPN
** HXF, \cite{zhang2013enhanced}, [[papers:zhang2013enhanced][zhang2013enhanced-paper]], hier mod
  1) The two QPSK symbols are then superimposed together to
     generate a 16-QAM symbol. The minimum distances between adjacent
     points of the two QPSK constellations are denoted by d1 and d2,
     respectively
  2) hierarchical 16-QAM modulation
*** Gray coded bit mapping in 16-QAM modulation
 1) http://www.dsplog.com/2008/06/05/16qam-bit-error-gray-mapping/ 


** OFDM.PON
   1)  from OFDM.PON.tex
\frametitle {Review of PON} 
        \begin{itemize}
          \item Broadband PON (BPON)~by ITU-T-1998 
        \item G-PON
          \item XG-PON  
% XG-PON = NG-PON1, /141104
            \item NG-PON2~(FSAN,~April 2012),~by Spiekman2013~\cite{spiekman2013active},~by Luo2012~(HW)~\cite{luo2012time} \\
             1) wavelength plan options; 2) power budget; 3) low cost tunable ONUs research. \\
           \item Symmetric TWDM-PON. \\
Yeh2010~(OOK)~\cite{Yeh2010using},~Luo2014~(PKU)~(64-QAM-OFDM,~4.167x6x4=100Gbps)~\cite{luo2014symmetric},~Yi2013~(SJTU)~\cite{Yi2013Symmetric},~Li2014~(SJTU)~\cite{Li2014Symmetric}.
        \end{itemize}


** DuobinaryModulationForOpticalSystems.pdf
  1) Duobinary modulation turns out to be a much better choice in this case since it is more resilient to dispersion
  2) Nyquist’s result tells us that in order to transmit R bits/sec
     with no inter-symbol interference (ISI), the minimum bandwidth
     required of the transmitted pulse is R/2 Hz. This result implies
     that duobinary pulses will have ISI.
  3) One way of generating duobinary signals is to digitally filter
     the data bits with a two-tap finite impulse response (FIR) filter
     with equal weights and then low-pass filter the resulting signal
     to obtain the analog waveform with the property in (1.3)
  4)  the output can take on one of three values: 0.5*(–1 + -1) = –1;
      –1 + 1 = 0; or 0.5*(1 + 1) = 1. Hence the duobinary signal is a
      three-level signal. 


** Format_conversion_javier_cano.pd
APPENDIX B: MATLAB code


* Review of OFDM-PON, OBM
** \cite{zhang2010novel}, ECDM-OFDM-PON, [2015-10-16 Fri]
   1. A novel ECDM-OFDM-PON architecture for next-generation optical access network
** \cite{yang2008107}, [[papers:yang2008107][yang2008107-paper]], OBM
 1) [2015-05-21 Thu]
** Review of OFDM-PON
\frametitle {Review of OFDM-PON} 
        \begin{itemize}
        \item General review by Cvijetic2012~\cite{cvijetic2012OFDM}
          %\item XG-PON
%             \item 8-chn+256-QAM by Shibata2014~(NTT Group)~\cite{Shibata2014256qam} \\
%             1) Pre-emphasize by a DSP-assisted RoF (8-chn); 2)
%             256-QAM~for~LTE-B~(64-QAM for LTE-A).
% %Pre-emph to increases the  number of wireless signals which meet the required
% EVM without increasing the average transmission power. sub-carrier spacing is 180 kHz, inter-OFDM is 25-MHz~(200-MHz BW), /141104
          \item DSB vs. SSB,~Lin2012~\cite{lin2012comparison}. \\
            % modulation only improve power efficiency. /141104
            power fading is negligible,~owing to low RF carrier,
            \item orthogonal band multiplexing~(OBM),~centralized laser\\
              Shieh2008,~\cite{Shieh2008coherent},~Qiu2011~\cite{Qiu2011OFDM},~Qian2009,~\cite{qian2009novel}
% #####  Shieh2008~\cite{Shieh2008107G},~Yang2009,~\cite{Yang2009Experimental}
        \end{itemize}




** \cite{lazaro2014flexible}, [[papers:lazaro2014flexible][lazaro2014flexible-paper]], WDM/Nyquist-PON
   1. Flexible PON Key technologies: Digital advanced modulation formats and devices
   2. Nyquist modulation with 20% of bandwidth reduction (4 GHz
      electrical filter bandwidth and 5 GHz Nyquist electrical
      spectrum bandwidth) obtains almost the same BER than OFDM with a
      full spectrum

** \cite{He2015full}, UWBoF
  1) Full-duplex multiband orthogonal frequency division multiplexing
     ultra-wideband over fiber system

** [KEY] ### *OBM, CENTRALIZED LASER, COHERENT DETECTION*, / [2014-11-05 Wed]
% #### KEY: 1) NEC:~QIAN,~Cvijetic,~Wei,~2) NTT:~3) UM:~Shieh,~Yang,~Ma,~(OTU,~141106)~4)
% TW:~YUANG

**  [YCH] ##### IMD~OFDM~by Ye, \cite{Cho2014cost}
% 4PAM,~\cite{Cho2010enhanced},  / [2014-11-06 Thu]
% spurious free dynamic range (SFDR), SFDR，F(FUD) VS. S(SPUR), 英文全称是 Spurious Free
% Dynamic range。意为无杂散动态范围，用于A/D转换器和D/A转换器(ADC和
% DAC)的指标。


** [KEY] [Shieh] ##### Shieh2008,~\cite{Shieh2008coherent}, [[papers:Shieh2008coherent][Shieh2008coherent-paper]]
%~Coherent optical OFDM: theory and design, 被引用次数:454
% print yet, /141107
% \cite{Shieh2008coherenti},~invited

** [#C] [KEY] [Shieh] Yang2009Experimental,~\cite{Yang2009Experimental}, [[papers:Yang2009Experimental][Yang2009Experimental-paper]]
%% ###orthogonal band multiplexing~(OBM),~OBM detail,  print yet 141106

%\cite{Shieh2008107G}
% OBM

***  Yang2009, OBM, 
% % ###/141106, to resolve ADC bandwidth bottleneck.~at least 15 GHz [5] and is not cost-effective to implement
% % even with the best commercial digital-to-analog converters (DACs)
% % 3) OBM-OFDM can be readily partitioned with electrical anti-alias
% % filters, and subsequently processed with lower-speed DAC/ADCs [6];
%  The entire bandwidth for 107-Gb/s OFDM signal is only 32 GHz, which is about 5 GHz
% tighter than that shown in the previous experiment [5]. This is
% because: 1) the guard band is reduced from 8 to 1 times of the
% subcarrier spacing and 2) the number of the pilot subcarriers is
% reduced from 8 to 4.

** NEC, Qian2011optical,~Cvijetic2010Orthogonal,~\cite{cvijetic2012OFDM}

% Qian2009,~\cite{qian2009novel}
%% ### NEC, coherent RX in OLT, OCS,  print yet, /141105
%%% Dayou Qian, Neda Cvijetic, Junqiang Hu, and Ting Wang

** NEC~Cvijetic2010~\cite{Cvijetic2010100G}, [[papers:Cvijetic2010100G][Cvijetic2010100G-paper]]
% IEEE Communications Magazine, /141105
% increasing spectral efficiency by polarization multiplexing

% Hekkala2012~\cite{Hekkala2012Predistortion}
% /141105

% ZTE2012OFDM.PON
% ###Xiangjun Xin, Xin2012key, pp43-47
%% two-carrrier scheme with 60 GHz rf space

** ### Qiu2011~\cite{Qiu2011OFDM}
%% invited, 
%%% WPT, orthogonal band multiplexing, centralized laser
%%% WDM-P2P, TDM-P2MP
%%%% The speed of every OFDM subcarrier is designed to be much lower,
%%%% so it is much more robust to the fiber dispersion that must be
%%%% overcome for high-speed optical fiber transmissions. 
%%%% For upstream transmission, the optical carrier of each ONU is
%%%% distributed from the same laser at the OLT, the so-called
%%%% centralized laser
%%%% coherent detection for better Rx sensitivity

% DC-OFDM by Sanya2014,~\cite{sanya2014dcacoofdm},~clipping noise can
% only affect the unused even subcarriers.
% OFDM is power-consuming.
% ACO-OFDM by Armstrong2006~\cite{Armstrong2006power}, 
% diversity combined-DC, /141104
% Two OFDM methods are often used for generating non-negative
% signals. One is called DC-biased Optical OFDM (DCO-OFDM) [3], [6]
% and the second, Asymmetricall Clipped Optical OFDM (ACO-OFDM)
% 如何产生单路的OFDM 实值信号成为研究重点,目前有两种解决方案,即直流偏
置光OFDM(DCO-OFDM)和非对称限幅OFDM(ACO-OFDM)。 


% OFDM-PON, pre-equalization (no equalization), \cite{Cvijetic2010Orthogonal}
% NEC Wang Group
% OFDM-OWC and Pre-Equalization by
% ### Saengudomlert2014~\cite{Saengudomlert2014benifits}
%### \cite{Guo2013novel}, pre-compresated, two inputs containing phase shifters. 

% OFDM-PON, by \cite{duong2007low}~Duong200810G~\cite{Duong200810G}
% complex conjugates, adaptive 4 to 64-QAM

% 16- and 64-QAM Formats, \cite{Lin2008Experimental}

% TCM coding, but not for PON, for RoF, /141104,  \cite{yang20091tbs}


**  [#C] paper of OBM-OFDM, Not yet
   CLOSED: [2015-02-02 周一 13:41]
   - State "DONE"       from ""           [2015-02-02 周一 13:41]

*** TODO [#B] zhang2014bandwidth, [[papers:zhang2014bandwidth][zhang2014bandwidth-paper]], SDN, OBM-OFDM
    1) Bandwidth-elastic OFDM-PON based on orthogonal band multiplexing
       for upstream transmissions
    2) http://www.sciencedirect.com/science/article/pii/S0030402613011996
    3) not yet, [2015-02-02 周一]

*** TODO zhang2012collective, [[papers:zhang2012collective][zhang2012collective-paper]]
    1) Collective reception of orthogonal band multiplexed data streams
       for OFDM-PON upstream transmissions
    2) http://www.sciencedirect.com/science/article/pii/S0030401812003963
    3) not yet, [2015-02-02 周一]


* USRP and FPGA

** @note

*** @fpga
    1. first by Bangor University, 2009, 6Gbps
       1. Altera Stratix II GX FPGAs
    2. Bell-Labs, CO-OFDM, 100Gbps
       1. several Xilinx Virtex 7 FPGAs (XC7VX1140T)
       2. 32-GS/s and higher sampling speed ADCs
    3. ZTE, 2015, 200Gbps, IM-DD, DMT
       1. four Altera EP4S100G FPGAs
       2. total 24 Xilinx 6VSX475 FPGAs

** \cite{kaneda2015field}, [[papers:kaneda2015field][kaneda2015field-paper]], 100Gbps, CO-OFDM :@Paper_BellLabs:
   1. Field demonstration of 100-Gb/s real-time coherent optical OFDM detection
   2. Four FPGAs are used to demodulate the 100-Gb/s CO-OFDM signal. 
   3. several Xilinx Virtex 7 FPGAs (XC7VX1140T)
   4. soft-core micro processor unit (MPU)
   5. 32-GS/s and higher sampling speed ADCs
*** [YJJ] \cite{kaneda2010real}, [[papers:kaneda2010real][kaneda2010real-paper]], @xliu, 3 RF OFDM subbands
  1) Real-time 2.5 GS/s coherent optical receiver for 53.3-Gb/s
     sub-banded OFDM

** \cite{giddings2010experimental}, [[papers:giddings2010experimental][giddings2010experimental-paper]], 11.25Gbps, :@Paper_BangorUni:
   1. Experimental demonstration of a record high 11.25 Gb/s real-time
      optical OFDM transceiver supporting 25km SMF end-to-end
      transmission in simple IMDD systems
   2. Altera Stratix II GX FPGAs
   3. joint test action group (JTAG)

*** \cite{giddings2009first}, [[papers:giddings2009first][giddings2009first-paper]], 6Gbps
    1. First experimental demonstration of 6Gb/s real-time optical OFDM
       transceivers incorporating channel estimation and variable power
       loading
    2. potentially in excess of 40Gb/s in the Altera Stratix II GX FPGA

*** \cite{tang2011real}
    1. Real-time optical OFDM transceivers for PON applications
    2. Bangor University is the first and only institute in the world
*** \cite{tang201417}, 17.125Gbps
    1. 17.125 Gb/s over 25km Transmissions of Real-time Dual-band
       Optical OFDM Signals Modulated by 1GHz RSOAs


** \cite{hwang2012design}, [[papers:hwang2012design][hwang2012design-paper]], FPGA
   1. Design and implementation of an optical OFDM baseband receiver in FPGA

** [#D] \cite{li2015real}, [[papers:li2015realization][li2015realization-paper]], 200Gbps, @yu_jianjun, :@Paper_ZTE:
   1. Real-time Direct-detection of Quad-carrier 200Gbps 16QAM-DMT
      with Directly Modulated Laser
   2. four Altera EP4S100G FPGAs
   3. total 24 Xilinx 6VSX475 FPGAs
*** [#D] \cite{li2015realization}, [[papers:li2015realization][li2015realization-paper]], Invited, 100Gbps
    1. Realization of real-time 100G 16QAM OFDM signal detection
*** \cite{li2013real}, [[papers:li2013real][li2013real-paper]], 50Gbps
    1. Real-time demonstration of DMT-based DDO-OFDM transmission and
       reception at 50Gb/s

*** \cite{xiao2014100}, 100Gbps
    1. 100-Gb/s single-band real-time coherent optical DP-16QAM-OFDM
       transmission and reception

** \cite{changsen2010design}, [[papers:changsen2010design][changsen2010design-paper]] 
   1. The Research of Multi-channel Data Level Conversion and
      Multiplexing Transmission System in Fiber Optic Communications

   2. Figure.2 10:2 combiner simulation
      1. finish the multi-channel video signal division multiplexingby
         10:2 combiner, the 10bit data signal into 2bit data signals

** \cite{morioka2014implementation}, [[papers:morioka2014implementation][morioka2014implementation-paper]], CPFSK-OFDM
 1) CPM is a general term for continuous phase modulation and it
    includes CPFSK, MSK, GMK and so on according to the CPM parameters
    such as modulation index
 2) USRP N210 as the front end of the software defined radio.


** \cite{marwanto2009experimental}, [[papers:marwanto2009experimental][marwanto2009experimental-paper]], USRP
** \cite{sanabria2012tcp},[[papers:sanabria2012tcp][sanabria2012tcp-paper]]

 1) TCP/IP communication between two USRP-E110


* Paper for Matlab

** CFO

*** [#C] \cite{van1997ml}, Est_ML_CFO_TO_OFDM.m
[2015-04-07 Tue]
** MS_sc_fde_dfe_base.m, FDE

*** \cite{benvenuto2002comparison}
 1) decision feedback equalizer (DFE)
 2) the matched filter bound (MFB) (performance with a matched filter receiver and no ISI)

*** \cite{falconer2002frequency}
