#+TITLE: Xiaoanh's CV
# Time-stamp: "Xiaoan1986 2016/01/15 23:17:56"
#+OPTIONS: toc:nil num:nil creator:nil
#+LaTeX_CLASS: slides
#+LaTeX_CLASS_OPTIONS: [captions=tableheading]

* COMMENT _求职意向_
*量化研究员/量化开发/量化分析*
* COMMENT _个人信息_
| Email:  ko-shaah-jv@ynu.jp                         | 手机: +86-13501809263 |
| Address: 上海市浦东新区金湘路399弄2号511室，201206 |                       |
* _个人简介_
2014年10月，本人经国家建设高水平大学公派研究生项目，获得了日本横浜国立
大学的无线通信专业的工学博士学位。毕业之后在上海贝尔的贝尔实验室担任5G
相关的 *研究科学家* 职位，取得了国际一流的研究成果。本人在模型设计、算法实现和性能优化等方面的技能及能力得到充分培养，熟悉及掌握与机器学习和算法设计等相关的专业技能。期间，我多次参加国际会议 (韩国ICACT、悉尼ICUWB、和多伦多CCSCI (*担任Session Chair*)) 进行交流和学习，从而进一步开阔了视野，全面提高了团队协作的能力。

* _自我评价_
- 本人性格开朗乐观，稳重踏实，待人真诚，意志顽强，积极奋进，不断进取；
- 工作积极配合，能吃苦耐劳，学习能力和适应能力很强，敢于挑战，勇于创新。

* _教育背景_
| 10/2011 -  10/2014 |  工学博士,  工学府通信工程专业, 日本横浜国立大学 (YNU, *国家公派*) |
| 10/2008 - 03/2011  | 理学硕士,  物理系光学专业, 上海交通大学 (SJTU, 985) |
| 09/2004 - 09/2008 | 理学学士,  物理系光信息科学与技术专业,  江南大学 (211) |

* _专业技能_
- 精通模型设计、算法实现和 性能优化
- 精通C 语言、C++、MATLAB、Linux、Python、Verilog/VHDL and Emacs (lisp)
- 自学统计学习方法和R语言
- 具备项目领导和团队合作能力
* _研究经历_
-  10/2011 - 10/2014, *博士 @Kohno Laboratory* in YNU (日本国家GCOE项目支持) 
    -  *基于60 GHz 超带宽无线通信技术UWB的车联网*: 为解决车联网的可靠
       性、 通信带宽受限、5G小基站高费用等核心问题，首次提出了一种新颖的60G UWB 光载无线电架构和最优算法(_带宽增长5倍且成本降低45%_)。
    -  *基于可见光通信的车联网*: 在车联网系统中为了加强高速化、安全化和多媒体云服务等功能，首次提出了一种新颖的基于可见光通信
       技术的架构模型和优化算法 (_容量增长9倍且有效范围扩充50%_)。

* _工作经历_
- 10/2014 - 至今, *研究科学家@贝尔实验室* (上海贝尔)
  - *基于信道聚合算法的10X 无线前端回传（5G)*: 为满足未来5G高密度和高容量的需求，首次提出了新颖的交织信道聚合算法 (_11倍容量提升且成本降低30%_)。
  - *下一代室内基于混合铜线（XG.FAST）和无线技术的宽带接入*: 为满足未来室内超宽带接入，首次提出了混合铜线和无线的MIMO信道模型 (_9倍容量提升且成本降低50%_)
  - *基于Python、C++和FPGA的综合平台验证*: 首次设计了基于Python的USRP 和FPGA的超宽带系统 (_100Gbps以上且7倍速率提升_).

* _所获奖励_
 | 10/2011 - 至今     | 国家建设高水平大学公派研究生 | 中国政府     |
 | 10/2008 - 07/2011  | 学业奖学金                   | 上海交通大学 |
 | 09/2005 - 09/2006  | 校优秀学生干部 (*TOP 2*)     | 江南大学     |
 | 09/2005 - 09/2007} | 学业奖学金  (*TOP 1 and 2* ) | 江南大学     |
* _语言能力_
 | 英语 | 六级 | 书写精通，口语熟练；博士期间学习和交流都是英语 |
 | 日语 | 二级 | 书写熟练，简单沟通                             |
  
* _兴趣爱好_
 | 运动 | 慢跑，健身                         |
 | 生活 | 旅游，单反                         |
 | 音乐 | Celine Dion，Kana Nishino 和 古典 |
* COMMENT _发表论文_ <<PUBS>>  
1. Xiaoan Huang, Ryuji Kohno, ICUWB2013, Sydney, Australia, September 15-18, 2013.
2. Xiaoan Huang, Ryuji Kohno, ICACT2013, Korea, Jan. 27-30, 2013.
3. Xiaoan Huang, Chika Sugimoto, and Ryuji Kohno, Cyber Journals, July Edition, 2013 Volume 3, Issue 7. 
4. Xiaoan Huang, Ryuji Kohno, CCSCI2014, Toronto, Canada, Jan. 10-12, 2014.
5. Xiaoan Huang, Chika Sugimoto, and Ryuji Kohno. Applied Mechanics and Materials. Vol. 548. 2014. 
6. Xiaoan Huang, Pengfei Zhu, et. al, Optics Communications 283, 2373-2377, 2010
* COMMENT _国际专利_
 1. Xiaoan Huang, “Interleaved Channel Aggregation Based  Multi-Intermedia Frequency Over Fiber System”, *Bell-Labs*, 2015.

#+BEGIN_SRC latex
  \clearpage
#+END_SRC
------


* COMMENT _JOB OBJECTIVE_
*Quantitative Researcher / Quantitative Developer / Quantitative Analyst*

* COMMENT _PERSONAL INFORMATION_
| Email:  ko-shaah-jv@ynu.jp                                                             | Cell-phone: +86-13501809263 |
| Address: Room 511, Building 2, No. 399 Jinxiang Road, Pudong, Shanghai, China, 201206. |                             |
* _SELF-ASSESSMENT_
    I have done world-class research as a research scientist at *Bell-Labs* in Shanghai (ASB)
    for about 1 years after I graduated from  Yokohama-National-University (YNU) in Japan as a Ph.D. selected by
    the *China State-Sponsored Postgraduate Study Abroad Program*. The
    algorithm design, implementation and optimization skills have been
    cultivated during the research experiences.
    In addition, through attending the international conferences (Korea, Sydney,
    and Toronto (*the role of session chair*)) and collaborating with
    colleagues in Bell-Labs, I have attained sufficient international communication and collaboration skills, capable of facing any challenges. 
* _EDUCATION_
    | 10/2011 - 10/2014 | Ph.D., Yokohama National University (YNU, *State-Sponsored*), Japan                     |
    | 10/2008 - 03/2011 | Master of Science, Dept. of Physics, Shanghai Jiao Tong University (SJTU, *985*), China |
    | 09/2004 - 09/2008 | Bachelor of Science, School of Science, Jiangnan University (JNU, *211*)                |
	  
* _PROFESSIONAL SKILLS_
  - Major in algorithm design, implementation, optimization
  - Proficient in C, C++, MATLAB, Linux, Python, Verilog/VHDL and Emacs (lisp)
  - Self-study statistical machine learning and R
  - Served as project leader, own good team spirit and project management capabilities.
* _RESEARCH EXPERIENCE_
-  10/2011 - 10/2014, *Ph. D @Kohno Laboratory* in YNU (under the support of the Japanese government GCOE project) 
    -  *60 GHz UWB based inter-vehicle communication for Internet of Things (IoT)*: Firstly
        proposed a novel 60-GHz ultra-wideband radio-over-fiber architecture  to resolve
        the bottleneck of limited bandwidth and high-cost of 5G dense
        base-stations (5-fold bandwidth increase and 45% cost reduction).
    -  *Visible light communication based inter-vehicle communication for IoT*: Firstly proposed a hybrid radio and visible
        light communication system employing visual-MIMO algorithm to
        enlarge the capacity and ensure the safety in intelligent
        transport system (9-fold capacity and 50% ranging increase). 

* _WORK EXPERIENCE_
- 10/2014 - PRESENT, *Research Scientist@BELL LABS in Shanghai* (Alcatel-Lucent in Shanghai)
    - *10X Mobile Front-haul (MFH) system for future 5G*: Firstly proposed a novel
      Interleaved Channel Aggregation  (ICA) algorithm to support high
      capacity for future 5G (11-fold capacity increase and 30% cost
      reduction)
    -  *XG-Fast for future indoor hybrid copper and wireless broadband
       access*: Firstly proposed a novel hybrid copper and wireless
       MIMO model to support high capacity for future indoor access
       (9-fold capacity increase and 50% cost reduction)	   
    - *Real-time demo for 10X MFH using Python based USRP and FPGA*:
      Firstly designed python-based USRP and FPGA to support
      high-bandwidth transmission (7-fold bandwidth increase)

* _AWARDS_
    | 10/2011 - 10/2014 | China State-Sponsored Postgraduate (China Scholarship Council) | YNU |
    | 10/2008 - 03/2011 | Excellent Academic Scholarship                  | SJTU |
    | 2005.09 - 2006.9  | Outstanding Student Leader of School (*TOP 2%*) | JNU  |
    | 09/2005 - 09/2007 | Excellent Academic Scholarship ( *TOP 1 and 2*) | JNU  |
* _LANGUAGES_
  | English | - expert in reading and writing; proficient in listening and speaking |
  | Japanese | - proficient in reading and writing;  average in listening and speaking |
* _INTERESTS_
  | Sports | Running, Fitness (Bench Press)         |
  | Life   | Tourism, and Photography (SLR)         |
  | Music  | Celine Dion, Kana Nishino and Classics |
* COMMENT _ [[PUBS][PUBLICATIONS]]_


* COMMENT _INTERNATIONAL PATENTS_
  1. Xiaoan Huang, “Interleaved Channel Aggregation Based
     Multi-Intermedia Frequency Over Fiber System”, *Bell-Labs*, 2015.

#+BEGIN_SRC latex
  \clearpage
#+END_SRC
------


* COMMENT _COVER LETTER_
Dear Recruiter, \\
Hello! \\

As a researcher in the world-class Bell Labs, Shanghai (ASB) for about 1 year,  I am always pursuing this job chance. \\

My unique background, the in-depth algorithm design  knowledge,
directly qualify me to apply for this job. I was selected by the China
State-Sponsored Postgraduate Study Abroad Program in October 2011 and
graduated as a Ph. D.  from Kohno Lab ( Prof. Ryuji Kohno (IEEE Fellow
and director of  Medical ICT Institute of NICT)), Yokohama National
University (YNU) in Japan in October, 2014.  From October 2014, I have
been working in Bell-Labs, Shanghai (ASB). \\

During the past 1 year in Bell-Labs, I have worked very hard and fast
as a new comer for my first career life. Under the collaboration and
discussion with my colleagues, my major abilities in algorithm design
are well employed in our platform. Up to now, a world-class patent has
been published and a novel architecture about an effective channel
aggregation for high-capacity 5G has been well designed. Besides that,
a Python, C++ and FPGA based demo has been well designed for to verify the
novel architecture. In addition, through attending the 3 international
conferences (Korea, Sydney, and Toronto), I have attained sufficient
international communication and collaboration skills, capable of facing any challenges. \\

I really hope an opportunity to talk with you or someone in your
company to discuss where my skills should be set would be of the greatest benefit to your company.  \\

Sincerely yours, \\

Xiaoan Huang  \\
January 16, 2016 \\
ko-shaah-jv@ynu.jp, 135-0180-9263
#+BEGIN_SRC latex
  \clearpage
#+END_SRC

------


* COMMENT _自荐书_
尊敬的领导：\\
您好！ \\
2014年10月，本人经国家建设高水平大学公派研究生项目，获得了日本横浜国立
大学 的无线通信专业的工学博士学位， 毕业后就职于上海贝尔的贝尔实验室，
从事研究科学家的工作。现我很荣幸向贵部门呈上我的自荐书，希望贵部门能成
为我工作生涯的第二职场。\\

我，男，汉族，1986 年05 月生，江西吉安人，2008 年06 月加入中国共产党，最高学历博士。2011 年10 月，
为了进一步拓宽专业知识面、提高实践及实验的能力，在国家留学基金委的资助及交大教授的推荐下，我选择日
本横浜国立大学—河野实验室攻读无线通信博士学位。在我的导师河野教授—Prof.
Ryuji Kohno (IEEE Fellow, 日本MICT所长) 的指导下，在UWB 无线通信的调制、编码和最优化方面取
得了些许成果。 \\

2014年10月起，在贝尔实验室工作的一年多期间，我进一步探索、研究通信理论知识，并在实验中反复检验，以第一负责人的身
份，我负责设计了挑战性的国际前沿课题： 基于交织信道聚合算法的5G无线前端回传系
统。 不仅如此，通过设计基于Python、C++ 和FPGA的综合平台实地验证了该方
案的可靠性。一年多时间，虽时光短暂，但面对前沿领域，我挑战自己，深入
研究无线通信相关方面的理论，不断挖掘，取得了一些成果。最为重要的是，在
部门同事的相互合作下，我无线通信专业方面的技术及能力得到充分锻炼。期间，我多次参加国际会议进行交流、学习，在多伦多的国际会议上
担当了Session Chair, 进一步开阔了视野，团队协作的能力得到全面提升。\\

本人性格开朗乐观、能吃苦耐劳、富有创新精神，能较快的接受新鲜事物，并迅速适应各种环境。工作中，我
待人真诚、善于沟通，能在最短的时间内融入到团队中，并积极学习各项前沿技术。我有很强的团队合作意识，能
较好的服从上级的管理，并配合好身边同事的工作。\\

我真心希望能成为贵部门的一名员工，在此恭候您的佳音！我将以饱满的热情投入到新的工作中，勤奋踏实、
团结协作，为贵团队的发展尽自己的绵薄之力。\\

此致 \\
敬礼! \\
自荐人：黄小安 \\
二O 一六年一月十六号 \\
ko-shaah-jv@ynu.jp, 135-0180-9263.
